public enum CourseContentError: Error, Equatable, Sendable {
    case resourceRootMissing
    case missingResource(String)
    case malformedJSON(String)
    case unsupportedSchema(document: String, found: Int)
    case unknownField(document: String, field: String)
    case invalidValue(document: String, field: String)
    case invalidID(kind: String, value: String)
    case duplicateID(kind: String, value: String)
    case defaultCourseMissing(String)
    case unknownCollection(courseID: String, collectionID: String)
    case unknownCourse(String)
    case unsafePath(String)
    case escapedRoot(String)
    case symbolicLink(String)
    case nonRegularFile(String)
    case unexpectedFiles(courseID: String)
    case metadataMismatch(courseID: String, field: String)
    case duplicateIntegrityPath(String)
    case undeclaredAudio(String)
    case byteCountMismatch(path: String, expected: Int, actual: Int)
    case manifestDigestMismatch(expected: String, actual: String)
    case audioDigestMismatch(path: String, expected: String, actual: String)
}
