// 570 headwords from Averil Coxhead's Academic Word List (AWL).
// Chinese meanings and phonetics are embedded from the MIT-licensed ECDICT dataset.
export type VocabularyEntry = readonly [word: string, meaning: string, sublist: number, phonetic: string];

export const WORDS: readonly VocabularyEntry[] = [
  ["abandon", "vt. 放弃, 抛弃, 遗弃, 使屈从, 沉溺, 放纵；n. 放任, 无拘束, 狂热", 8, "ə'bændən"],
  ["abstract", "a. 抽象的, 深奥的；n. 摘要, 抽象概念", 6, "'æbstrækt"],
  ["academy", "n. 学院, 院校, 学会", 5, "ə'kædəmi"],
  ["access", "n. 通路, 入口, 接近, 进入, 使用权, 发作；vt. 访问, 存取, 接近, 使用", 4, "'ækses"],
  ["accommodate", "vt. 使适应, 调和, 通融, 容纳, 向...提供；vi. 适应", 9, "ə'kɒmədeit"],
  ["accompany", "vt. 陪伴, 伴随, 补充, 为...伴奏；vi. 伴奏, 伴唱", 8, "ə'kʌmpəni"],
  ["accumulate", "v. 积聚, 堆积", 8, "ə'kju:mjuleit"],
  ["accurate", "a. 正确的, 精确的", 6, "'ækjurət"],
  ["achieve", "vt. 完成, 达到；vi. 如愿以偿", 2, "ə'tʃi:v"],
  ["acknowledge", "vt. 承认, 告知收悉, 答谢, 报偿", 6, "ək'nɒlidʒ"],
  ["acquire", "vt. 获得, 学到", 2, "ə'kwaiə"],
  ["adapt", "vt. 使适应, 改编；vi. 适应", 7, "ə'dæpt"],
  ["adequate", "a. 适当的, 足够的", 4, "'ædikwət"],
  ["adjacent", "a. 毗连的, 邻近的, 连接的", 10, "ə'dʒeisənt"],
  ["adjust", "vt. 调整, 使适应于, 校准；vi. 适应于, 被调节, 相互熟悉而适应", 5, "ə'dʒʌst"],
  ["administration", "n. 行政, 管理, 政府机关", 2, "əd.mini'streiʃən"],
  ["adult", "n. 成人, 成虫；a. 成年的, 成熟的", 7, "'ædʌlt"],
  ["advocate", "n. 提倡者, 拥护者；vt. 主张, 提倡", 7, "'ædvəkeit"],
  ["affect", "vt. 影响, 感动, 假装, 模仿, 爱好, 倾向于；n. 自觉感情", 2, "ə'fekt"],
  ["aggregate", "n. 合计, 总计, 聚集体；a. 合计的, 聚集的", 6, "'ægrigət"],
  ["aid", "n. 帮助, 外援, 助手；vt. 援助, 帮助, 有助于", 7, "eid"],
  ["albeit", "conj. 尽管, 虽然", 10, "ɔ:l'bi:it"],
  ["allocate", "vt. 分派, 分配", 6, "'æləukeit"],
  ["alter", "v. 改变", 5, "'ɒ:ltə"],
  ["alternative", "n. 两者择一, 供替代的选择；a. 两者择一的, 供选择的", 3, "ɒ:l'tə:nətiv"],
  ["ambiguous", "a. 不明确的, 模棱两可的", 8, "æm'bigjuəs"],
  ["amend", "vt. 修改, 改善, 改良；vi. 改过自新", 5, "ə'mend"],
  ["analogy", "n. 相似, 类似", 9, "ə'nælədʒi"],
  ["analyse", "vt. 分析, 细察, 分解", 1, "'ænəlaiz"],
  ["annual", "n. 年刊, 年报；a. 每年的, 一年一次的, 全年的, 一年生的", 4, "'ænjuəl"],
  ["anticipate", "vt. 预期, 占先, 加速, 提前使用", 9, "æn'tisipeit"],
  ["apparent", "a. 清晰可见的, 显然的, 表面上的", 4, "ə'pærənt"],
  ["append", "vt. 附加, 增补, 盖章；当程序执行时, DOS将在所设定的磁盘路径中查找不在当前路径下的文件", 8, "ə'pend"],
  ["appreciate", "vt. 赏识, 鉴别, 为...而感激, 领会, 欣赏；vi. 增值, 涨价", 8, "ə'pri:ʃieit"],
  ["approach", "n. 接近, 入门；vt. 接近, 近似, 找...商量", 1, "ə'prəutʃ"],
  ["appropriate", "a. 适当的", 2, "ə'prəupriət"],
  ["approximate", "a. 大约的, 接近的, 近似的；vt. 接近, 使接近, 粗略估计", 4, "ə'prɒksimət"],
  ["arbitrary", "a. 任意的, 武断的, 专治的, 霸道的", 8, "'ɑ:bitrəri"],
  ["area", "n. 区域, 面积, 范围, 空地", 1, "'eəriə"],
  ["aspect", "n. 外观, 方面, 面貌, 方向", 2, "'æspekt"],
  ["assemble", "vt. 集合, 收集, 装配；vi. 集合", 10, "ə'sembl"],
  ["assess", "vt. 估定, 对...征税, 评定", 1, "ə'ses"],
  ["assign", "vt. 分配, 指派, 赋值", 6, "ə'sain"],
  ["assist", "n. 帮助, 协助；vt. 帮助, 促进", 2, "ə'sist"],
  ["assume", "vt. 假定, 承担, 呈现；vi. 装腔作势, 僭越", 1, "ə'sju:m"],
  ["assure", "vt. 保证, 使确信, 弄清楚, 担保", 9, "ə'ʃuə"],
  ["attach", "vt. 附上, 使依附, 使附属, 使喜爱, 系, 缚；vi. 附属, 归属, 联系在一起", 6, "ə'tætʃ"],
  ["attain", "vt. 达到, 获得；vi. 达到", 9, "ə'tein"],
  ["attitude", "n. 态度, 看法, 姿势", 4, "'ætitju:d"],
  ["attribute", "n. 属性, 标志, 定语；vt. 把...归于, 认为...属于", 4, "ə'tribju:t"],
  ["author", "n. 作家, 作家的著作, 创始人", 6, "'ɒ:θə"],
  ["authority", "n. 权力, 当权者, 当局, 权威, 专家", 1, "ɒ:'θɒriti"],
  ["automate", "vt.vi. (使)自动化", 8, "'ɔ:təmeit"],
  ["available", "a. 可利用的, 可获得的, 有效的", 1, "ə'veiləbl"],
  ["aware", "a. 知道的, 有觉悟的", 5, "ə'weə"],
  ["behalf", "n. 利益, 方面", 9, "bi'hɑ:f"],
  ["benefit", "n. 利益；vt. 有益于", 1, "'benifit"],
  ["bias", "n. 偏见, 斜纹；a. 偏斜的", 8, "'baiəs"],
  ["bond", "n. 捆绑物, 结合, 债券, 契约, 粘合剂, 保证人, 键, 关栈保留；vt. 存入关栈, 使黏合", 6, "bɒnd"],
  ["brief", "n. 摘要, 简报；a. 简短的, 短暂的", 6, "bri:f"],
  ["bulk", "n. 大小, 体积, 大块, 大多数；vt. 显得大, 显得重要", 9, "bʌlk"],
  ["capable", "a. 有能力的, 能的, 能干的", 6, "'keipəbl"],
  ["capacity", "n. 容量, 能力, 才能, 资格", 5, "kə'pæsiti"],
  ["category", "n. 种类, 类项", 2, "'kætigəri"],
  ["cease", "n. 停止；v. 停止, 终了", 9, "si:s"],
  ["challenge", "n. 挑战, 盘问；vt. 向...挑战, 要求, 怀疑", 5, "'tʃælindʒ"],
  ["channel", "n. 海峡, 航道, 频道；vt. 引导, 在...上挖沟, 形成河道", 7, "'tʃænəl"],
  ["chapter", "n. 章, 篇, 重要章节", 2, "'tʃæptə"],
  ["chart", "n. 图表, 海图；vt. 制成图表", 8, "tʃɑ:t"],
  ["chemical", "n. 化学药品；a. 化学的, 化学上用的", 7, "'kemikl"],
  ["circumstance", "n. 环境, 状况, 事件", 3, "'sə:kəmstəns"],
  ["cite", "vt. 引用, 引证, 表彰", 6, "sait"],
  ["civil", "a. 市民的, 公民的, 有礼貌的", 4, "'sivəl"],
  ["clarify", "vi. 澄清, 阐明；vt. 使明晰", 8, "'klærifai"],
  ["classic", "n. 古典作品, 杰作, 大艺术家；a. 第一流的, 最优秀的, 古典的", 7, "'klæsik"],
  ["clause", "n. 子句, 条款", 5, "klɒ:z"],
  ["code", "n. 代码, 密码, 法规, 法典；vt. 把...编码", 4, "kəud"],
  ["coherent", "a. 互相耦合的, 清晰的, 明了的，凝聚性的, 连贯的", 9, "kəu'hiərənt"],
  ["coincide", "vi. 一致, 符合", 9, ".kəuin'said"],
  ["collapse", "n. 崩溃, 倒塌, 虚脱；vi. 倒塌, 崩溃, 瓦解", 10, "kə'læps"],
  ["colleague", "n. 同事, 同僚", 10, "'kɒli:g"],
  ["commence", "v. (使)开始, 得学位", 9, "kə'mens"],
  ["comment", "n. 注解, 批评, 评论, 备注；vi. 评论, 注解", 3, "'kɒment"],
  ["commission", "n. 委任状, 任官令, 所委职责, 佣金, 犯, 委托, 所托之事；vt. 委任, 委托制作, 使服役", 2, "kə'miʃən"],
  ["commit", "vt. 委托(托付), 犯罪, 指派...作战, 使承担义务", 4, "kə'mit"],
  ["commodity", "n. 农产品, 商品, 有用的物品", 8, "kə'mɒditi"],
  ["communicate", "vt. 显露, 传达, 感染；vi. 通讯", 4, "kə'mju:nikeit"],
  ["community", "n. 社区, 公众, 共有, 共同体", 2, "kə'mju:niti"],
  ["compatible", "a. 能共处的, 可并立的, 适合的", 9, "kəm'pætəbl"],
  ["compensate", "v. 偿还, 补偿, 付报酬", 3, "'kɒmpenseit"],
  ["compile", "vt. 编译, 编辑, 编纂, 收集", 10, "kəm'pail"],
  ["complement", "n. 补足物, 补语, 补数；vt. 补充, 补足", 8, "'kɒmplimənt"],
  ["complex", "n. 综合体, 情结, 络合物；a. 复杂的, 组合的", 2, "kəm'pleks"],
  ["component", "n. 元件, 组件, 成分；a. 组成的, 构成的", 3, "kəm'pəunənt"],
  ["compound", "n. 混合物, 复合词, 化合物, 院子；a. 复合的, 混合的, 化合的", 5, "kəm'paund"],
  ["comprehensive", "a. 广泛的, 有理解力的, 综合的", 7, ".kɒmpri'hensiv"],
  ["comprise", "vt. 包含, 构成", 7, "kəm'praiz"],
  ["compute", "v. 计算, 估算；n. 计算, 估算", 2, "kəm'pju:t"],
  ["conceive", "vt. 构思, 认为；vi. 怀孕", 10, "kən'si:v"],
  ["concentrate", "n. 浓缩, 精选；v. 集中, 专心", 4, "'kɒnsəntreit"],
  ["concept", "n. 观念, 概念", 1, "'kɒnsept"],
  ["conclude", "vt. 结束, 作结论, 推断；vi. 结束, 推断", 2, "kən'klu:d"],
  ["concurrent", "n. 同时发生的事件；a. 同时发生的, 一致的", 9, "kən'kʌrənt"],
  ["conduct", "n. 行为, 举动, 指导；vt. 为人, 指挥, 管理, 实施", 2, "'kɔndʌkt, -dəkt"],
  ["confer", "vt. 授予, 带来；vi. 协商", 4, "kən'fə:"],
  ["confine", "vt. 限制, 使不外出, 禁闭；vi. 邻接, 交界", 9, "kən'fain"],
  ["confirm", "vt. 证实, 确定, 批准, 使巩固", 7, "kən'fə:m"],
  ["conflict", "n. 战斗, 冲突, 矛盾, 争执；vi. 争执, 战斗, 冲突, 抵触", 5, "'kɒnflikt"],
  ["conform", "vt. 使一致, 使遵守, 使符合；vi. 一致, 符合, 适应", 8, "kən'fɒ:m"],
  ["consent", "n. 同意, 许可；vi. 同意, 赞同", 3, "kən'sent"],
  ["consequent", "n. 随后发生的事情, 结果；a. 作为结果的, 合乎逻辑的", 2, "'kɒnsikwənt"],
  ["considerable", "a. 相当的, 可观的, 重要的", 3, "kən'sidərəbl"],
  ["consist", "vi. 组成, 存在于, 一致", 1, "kən'sist"],
  ["constant", "n. 常数, 恒量；a. 不变的, 一定的, 时常的", 3, "'kɒnstənt"],
  ["constitute", "vt. 构成, 组成, 任命", 1, "kən'stitjut"],
  ["constrain", "vt. 强迫, 限制, 关押", 3, "kən'strein"],
  ["construct", "vt. 构造, 建造, 对...进行构思, 作图；n. 构成物", 2, "kən'strʌkt"],
  ["consult", "vi. 商讨, 商量, 协商, 会诊；vt. 向...请教, 查阅, 考虑", 5, "kən'sʌlt"],
  ["consume", "vt. 消耗, 消费, 消灭；vi. 耗尽, 毁灭", 2, "kən'sju:m"],
  ["contact", "n. 联系, 交际, 熟人, 接触；vi. 接触, 联系", 5, "'kɒntækt"],
  ["contemporary", "n. 同时代的人；a. 同时代的, 属于同一时期的", 8, "kən'tempərəri"],
  ["context", "n. 上下文, 背景, 来龙去脉；n. 上下文", 1, "'kɒntekst"],
  ["contract", "n. 合约, 婚约, 契约；vt. 使皱缩, 使缩短, 感染, 订约, 缔结", 1, "'kɒntrækt"],
  ["contradict", "vt. 反驳, 与...抵触, 与...矛盾；vi. 反驳", 8, ".kɒntrə'dikt"],
  ["contrary", "a. 相反的, 矛盾的, 对立的；n. 相反, 对立面", 7, "'kɒntrəri"],
  ["contrast", "n. 差别, 对比, 对照物；vt. 使对比", 4, "kən'træst"],
  ["contribute", "vt. 有助于, 捐助, 投稿；vi. 出力, 捐献, 投稿", 3, "kən'tribju:t"],
  ["controversy", "n. 论争, 辩论, 论战, 争论", 9, "'kɒntrəvə:si"],
  ["convene", "vt. 集合, 召集, 召唤；vi. 聚集, 集合", 3, "kən'vi:n"],
  ["converse", "n. 相反的事物, 倒, 逆向；a. 相反的, 逆向的, 颠倒的", 9, "kən'və:s"],
  ["convert", "n. 皈依者, 改变宗教信仰者；vt. 使改变信仰, 转换, 兑换, 倒置", 7, "kən'və:t"],
  ["convince", "vt. 说服, 使相信", 10, "kən'vins"],
  ["cooperate", "vi. 合作, 协力, 配合", 6, "kəu'ɒpəreit"],
  ["coordinate", "n. 同等的人(或物), 坐标；a. 同等的, 并列的", 3, "kəu'ɒ:dineit"],
  ["core", "n. 核心, 果心, 要点；vt. 挖...的核", 3, "kɒ:"],
  ["corporate", "a. 社团的, 合伙的, 公司的", 3, "'kɒ:pərit"],
  ["correspond", "vi. 符合, 通信, 相当", 3, ".kɒri'spɒnd"],
  ["couple", "n. 对, 夫妇, 数个；vt. 使成双, 连接, 使成婚, 把...联系起来", 7, "'kʌpl"],
  ["create", "vt. 创造, 建造, 引起, 任命", 1, "kri:'eit"],
  ["credit", "n. 信用, 信任, 荣誉, 贷款, 学分；vt. 归功于, 赞颂, 信任, 相信", 2, "'kredit"],
  ["criteria", "pl. 标准", 3, "krai'tiəriə"],
  ["crucial", "a. 决定性的, 重要的, 严厉的", 8, "'kru:ʃəl"],
  ["culture", "n. 文化, 修养, 耕种；vt. 耕种, 培养", 2, "'kʌltʃə"],
  ["currency", "n. 货币, 通货, 流通, 通用", 8, "'kʌrənsi"],
  ["cycle", "n. 周期, 循环, 自行车, 一段时间, 整套；vi. 循环, 轮转, 骑自行车", 4, "'saikl"],
  ["data", "pl. 资料, 数据", 1, "'deitə"],
  ["debate", "n. 辩论, 讨论；v. 争论, 辩论", 4, "di'beit"],
  ["decade", "n. 十年, 十", 7, "'dekeid"],
  ["decline", "n. 衰退, 跌落, 下降；vt. 使降低, 婉谢", 5, "di'klain"],
  ["deduce", "vt. 推论, 演绎出", 3, "di'dju:s"],
  ["define", "vt. 定义, 规定, 使明确", 1, "di'fain"],
  ["definite", "a. 明确的, 一定的", 7, "'definit"],
  ["demonstrate", "vt. 示范, 证明；vi. 示威", 3, "'demənstreit"],
  ["denote", "vt. 指示, 表示", 8, "di'nəut"],
  ["deny", "v. 否认, 拒绝", 7, "di'nai"],
  ["depress", "vt. 使沮丧, 压低, 降低, 使萧条", 10, "di'pres"],
  ["derive", "vt. 得自；vi. 起源", 1, "di'raiv"],
  ["design", "n. 设计, 图样, 方案, 企图；v. 设计, 计划", 2, "di'zain"],
  ["despite", "n. 轻视, 憎恨；prep. 虽然, 尽管", 4, "di'spait"],
  ["detect", "vt. 发现, 察觉, 探测", 8, "di'tekt"],
  ["deviate", "vi. 脱离, 偏离；vt. 使偏离", 8, "'di:vieit"],
  ["device", "n. 装置, 设计, 策略, 发明物, 设备", 9, "di'vais"],
  ["devote", "vt. 投入于, 献身", 9, "di'vəut"],
  ["differentiate", "v. 区别, 区分", 7, ".difə'renʃieit"],
  ["dimension", "n. 尺寸, 次元, 面积, 维数；vt. 标出尺寸", 4, "dai'menʃən"],
  ["diminish", "v. (使)减少, (使)变小", 9, "di'miniʃ"],
  ["discrete", "a. 不连续的, 离散的", 5, "dis'kri:t"],
  ["discriminate", "v. 区别, 差别待遇", 6, "dis'krimineit"],
  ["displace", "vt. 移置, 替换, 转移", 8, "dis'pleis"],
  ["display", "n. 显示, 陈列, 炫耀, 显示器；vt. 陈列, 显示, 表现, 夸示", 6, "dis'plei"],
  ["dispose", "vt. 处理, 排列, 布置；vi. 处置", 7, "dis'pəuz"],
  ["distinct", "a. 清楚的, 显著的, 不同的", 2, "dis'tiŋkt"],
  ["distort", "vt. 扭曲, 歪曲", 9, "dis'tɒ:t"],
  ["distribute", "vt. 分配, 散布, 分发", 1, "di'stribju:t"],
  ["diverse", "a. 不同的, 变化多的", 6, "dai'və:s"],
  ["document", "n. 文件, 公文, 文档；vt. 证明, 为...引证", 3, "'dɒkjumənt"],
  ["domain", "n. 领域, 领土, 产业, 范围", 6, "dəu'mein"],
  ["domestic", "a. 家庭的, 国内的, 驯养的", 4, "dəu'mestik"],
  ["dominate", "v. 支配, 占优势", 3, "'dɒmineit"],
  ["draft", "n. 气流, 草稿, 汇票, 草案；vt. 起草, 征兵", 5, "dræft. drɑ:ft"],
  ["drama", "n. 戏剧, 戏剧艺术", 8, "'drɑ:mə"],
  ["duration", "n. 持续时间, 持续", 9, "dju'reiʃən"],
  ["dynamic", "a. 动态的, 有活力的, 有力的, 动力的, 不断变化的；n. 动力, 动态", 7, "dai'næmik"],
  ["economy", "n. 经济, 理财, 节约", 1, "i'kɒnəmi"],
  ["edit", "vt. 编辑, 编校, 修订, 剪辑", 6, "'edit"],
  ["element", "n. 元件, 元素, 要素", 2, "'elimənt"],
  ["eliminate", "vt. 除去, 排除, 剔除, 消除", 7, "i'limineit"],
  ["emerge", "vi. 浮现, 形成, 出现, (事实)显露", 4, "i'mə:dʒ"],
  ["emphasis", "n. 强调, 加强, 重点, 强语气", 3, "'emfəsis"],
  ["empirical", "a. 完全跟据经验的, 经验主义的", 7, "em'pirikəl"],
  ["enable", "vt. 使能够", 5, "i'neibl"],
  ["encounter", "n. 相会, 相遇, 遭遇；vt. 遇见, 邂逅, 会战", 10, "in'kauntə"],
  ["energy", "n. 精力, 精神, 活力, 能量", 5, "'enədʒi"],
  ["enforce", "vt. 强迫, 执行, 坚持", 5, "in'fɒ:s"],
  ["enhance", "vt. 提高, 加强, 增加", 6, "in'hæns"],
  ["enormous", "a. 巨大的, 庞大的", 10, "i'nɒ:məs"],
  ["ensure", "vt. 确定, 保证, 担保, 保护", 3, "in'ʃuə"],
  ["entity", "n. 实体, 实存物, 存在", 5, "'entiti"],
  ["environment", "n. 环境, 外界, 围绕", 1, "in'vairənmənt"],
  ["equate", "vt. 使相等, 视为平等；vi. 等同", 2, "i'kweit"],
  ["equip", "vt. 装备, 配备", 7, "i'kwip"],
  ["equivalent", "n. 同等物, 等价物, 相等物；a. 相等的, 相当的, 同意义的", 5, "i'kwivələnt"],
  ["erode", "vt. 腐蚀, 侵蚀；vi. 受腐蚀", 9, "i'rəud"],
  ["error", "n. 错误, 过失, 失误, 误差", 4, "'erə"],
  ["establish", "vt. 建立, 确立, 制定；vi. 移植生长", 1, "i'stæbliʃ"],
  ["estate", "n. 不动产, (人生的)阶段, 阶层, 财产", 6, "i'steit"],
  ["estimate", "n. 估计, 判断；vt. 估计, 评价, 判断", 1, "'estimeit"],
  ["ethic", "n. 道德规范, 伦理", 9, "'eθik"],
  ["ethnic", "a. 人种的, 种族的", 4, "'eθnik"],
  ["evaluate", "vt. 评估, 评价, 赋值", 2, "i'væljueit"],
  ["eventual", "a. 最后的, 终于的", 8, "i'ventʃuəl"],
  ["evident", "a. 显然的, 明显的", 1, "'evidənt"],
  ["evolve", "vi. 进展, 进化, 展开；vt. 使发展, 使推断出, 使进化", 5, "i'vɒlv"],
  ["exceed", "vt. 超过, 超越, 胜过；vi. 超过其他", 6, "ik'si:d"],
  ["exclude", "vt. 除外, 排除, 排斥", 3, "iks'klu:d"],
  ["exhibit", "n. 显示, 显现, 展览品, 陈列品, 展览；vt. 展现, 陈列, 展览", 8, "ig'zibit"],
  ["expand", "vt. 使膨胀, 详述, 扩张；vi. 张开, 发展", 5, "ik'spænd"],
  ["expert", "n. 专家, 行家；a. 老练的, 内行的, 专门的", 6, "'ekspə:t"],
  ["explicit", "a. 详述的, 清楚的, 直言的", 6, "ik'splisit"],
  ["exploit", "n. 功绩, 勋绩；vt. 开发, 利用, 开拓, 剥削", 8, "'eksplɒit"],
  ["export", "n. 输出品, 输出；vt. 输出, 出口", 1, "ik'spɒ:t"],
  ["expose", "vt. 使暴露, 使曝光, 揭穿, 陈列", 5, "ik'spəuz"],
  ["external", "n. 外部, 外面；a. 外部的, 客观的, 表面的", 5, "ik'stə:nl"],
  ["extract", "n. 榨出物, 精汁, 摘录, 选段；vt. (费力地)取出, 采掘, 榨取, 摘录, 吸取", 7, "ik'strækt"],
  ["facilitate", "vt. 使容易, 促进, 帮助", 5, "fə'siliteit"],
  ["factor", "n. 因素, 因数, 系数, 基因, 代理人", 1, "'fæktə"],
  ["feature", "n. 面孔的一部分(如眼、口等), 特征, 容貌, 特色, 特写；vt. 是...的特色, 特写, 放映", 2, "'fi:tʃə"],
  ["federal", "a. 联邦的, 联合的, 同盟的", 6, "'fedərəl"],
  ["fee", "n. 费用, 小费, 封地, 所有权；vt. 付费给", 6, "fi:"],
  ["file", "n. 档案, 公文箱, 文件夹, 文件, 卷宗, 锉刀；vi. 列队行进, 用锉刀做", 7, "fail"],
  ["final", "n. 期末考试, 结局, 决赛；a. 最后的, 终极的, 决定性的", 2, "'fainl"],
  ["finance", "n. 财政, 财务；vt. 供给...经费, 负担经费", 1, "fai'næns"],
  ["finite", "a. 有限的, 有穷的, 限定的；n. 有限物", 7, "'fainait"],
  ["flexible", "a. 易曲的, 灵活的, 柔顺的, 能变形的, 可通融的", 6, "'fleksəbl"],
  ["fluctuate", "vi. 变动, 起伏, 动摇；vt. 使波动, 使动摇", 8, "'flʌktʃueit"],
  ["focus", "n. 焦点, 焦距；vi. 聚焦, 注视", 2, "'fəukəs"],
  ["format", "n. 开本, 版式, 形式, 格式；vt. 格式化", 9, "'fɒ:mæt"],
  ["formula", "n. 客套语, 公式, 准则", 1, "'fɒ:mjulə"],
  ["forthcoming", "a. 即将来临的；n. 来临", 10, "'fɒ:θ'kʌmɑŋ"],
  ["foundation", "n. 基础, 根据, 建立", 7, "faun'deiʃən"],
  ["found", "vt. 建立, 创立, 铸造；find的过去式和过去分词", 9, "faund"],
  ["framework", "n. 结构, 骨架, 参照标准, 准则, 观点", 3, "'freimwə:k"],
  ["function", "n. 官能, 职务, 功能, 函数；vi. 活动, 运行, 行使职责", 1, "'fʌŋkʃən"],
  ["fund", "n. 基金, 资金, 存款, 财源, 贮藏；vt. 提供资金, 积累", 3, "fʌnd"],
  ["fundamental", "n. 基本原理, 原则, 基波；a. 基本的, 重要的, 原音的", 5, ".fʌndə'mentəl"],
  ["furthermore", "adv. 此外, 而且", 6, "'fə:ðə'mɒ:"],
  ["gender", "n. 性；vt. 产生", 6, "'dʒendə"],
  ["generate", "vt. 产生, 发生, 导致", 5, "'dʒenəreit"],
  ["generation", "n. 一代, 一世, 产生", 5, ".dʒenə'reiʃən"],
  ["globe", "n. 球, 球状物, 地球仪, 天体；v. (使)成球状", 7, "gləub"],
  ["goal", "n. 目标, 终点, 得分, 球门, 守门员；vi. 攻门, 射门得分", 4, "gəul"],
  ["grade", "n. 等级, 年级, 阶段, 成绩, 程度, 坡度, 斜坡；vt. 分等, 分级, 评分", 7, "greid"],
  ["grant", "n. 授予, 授予物, 允许；vt. 允许, 承认, 授与", 4, "grænt"],
  ["guarantee", "n. 担保, 抵押品, 保证书；vt. 保证, 担保", 7, ".gærən'ti:"],
  ["guideline", "n. 指导路线, 方针, 指标", 8, "'gaidlain"],
  ["hence", "adv. 因此, 从此", 4, "hens"],
  ["hierarchy", "n. 等级制度, 僧侣统治, 等级体系", 7, "'haiərɑ:ki"],
  ["highlight", "n. 加亮区, 精彩场面；vt. 加亮, 使显著, 以强光照射, 突出", 8, "'hailait"],
  ["hypothesis", "n. 假设", 4, "hai'pɒθəsis"],
  ["identical", "a. 同一的, 恒等的, 完全相同的", 7, "ai'dentikəl"],
  ["identify", "vt. 识别, 认为...等同于, 确定, 使参与；vi. 一致, 认同", 1, "ai'dentifai"],
  ["ideology", "n. 思想体系, 意识形态, 观念学, 空论", 7, ".aidi'ɒlədʒi"],
  ["ignorance", "n. 无知, 愚味", 6, "'ignərəns"],
  ["illustrate", "vt. 举例说明, 作图解, 阐明；vi. 举例说明", 3, "'iləstreit"],
  ["image", "n. 影像, 肖像, 想象, 图像, 形象, 翻版；vt. 作...的像, 反映, 想象, 象征", 5, "'imidʒ"],
  ["immigrate", "vt. 使移居入境；vi. 移入", 3, "'imigreit"],
  ["impact", "n. 冲击, 冲突, 影响, 效果；vt. 挤入, 撞击, 压紧, 对...发生影响", 2, "'impækt"],
  ["implement", "n. 工具, 器具, 手段；vt. 实现, 使生效, 执行", 4, "'implimənt"],
  ["implicate", "vt. 涉及, 含意, 暗示, 牵连；n. 包含的东西", 4, "'implikeit"],
  ["implicit", "a. 暗示的, 含蓄的, 固有的, 绝对的", 8, "im'plisit"],
  ["imply", "vt. 暗示, 意味", 3, "im'plai"],
  ["impose", "vt. 征(税), 把...强加于, 以...欺骗；vi. 利用, 欺骗, 施加影响", 4, "im'pəuz"],
  ["incentive", "n. 动机；a. 激励的", 6, "in'sentiv"],
  ["incidence", "n. 发生, 发生率, 影响, 负担者, 入射, 倾角", 6, "'insidəns"],
  ["incline", "n. 倾斜, 斜坡, 斜面；vt. 使倾向于, 使倾斜", 10, "in'klain"],
  ["income", "n. 收入, 收益, 流入", 1, "'inkʌm"],
  ["incorporate", "a. 合并的, 组成公司的, 一体化的；vt. 吸收, 合并, 使组成公司, 体现", 6, "in'kɒ:pəreit"],
  ["index", "n. 索引, 指针, 指数, 指标；vt. 编入索引中, 指出", 6, "'indeks"],
  ["indicate", "vt. 显示, 象征, 指示, 指出", 1, "'indikeit"],
  ["individual", "n. 人, 个人, 个体；a. 个别的, 个人的, 独特的", 1, ".indi'vidʒuəl"],
  ["induce", "vt. 引诱, 招致, 归纳出, 感应", 8, "in'dju:s"],
  ["inevitable", "a. 不可避免的, 必然的", 8, "in'evitəbl"],
  ["infer", "vt. 推论出, 推断；vi. 作推论", 7, "in'fə:"],
  ["infrastructure", "n. 基础结构, 基础设施", 8, "'infrəstrʌktʃə"],
  ["inherent", "a. 固有的, 与生俱来的", 9, "in'hiərənt"],
  ["inhibit", "vt. 禁止, 抑制；vi. 起抑制作用", 6, "in'hibit"],
  ["initial", "n. 字首, 首字母；a. 开始的, 最初的, 字首的", 3, "i'niʃəl"],
  ["initiate", "n. 入会, 开始；a. 新加入的", 6, "i'niʃieit"],
  ["injure", "vt. 伤害, 损害, 使受冤屈", 2, "'indʒə"],
  ["innovate", "vi. 改革, 创新", 7, "'inəuveit"],
  ["input", "n. 输入, 输入电路；vt. 输入", 6, "'input"],
  ["insert", "n. 插入物；vt. 插入, 把(人造卫星)射入(轨道), 添写", 7, "in'sə:t"],
  ["insight", "n. 察看, 洞察力, 见识", 9, "'insait"],
  ["inspect", "vt. 检查, 检阅, 检验；vi. 检查", 8, "in'spekt"],
  ["instance", "n. 建议, 情况, 例子, 场合；vt. 引以为例, 举例说明", 3, "'instəns"],
  ["institute", "n. 学会, 学院, 协会；vt. 创立, 开始, 制定, 任命", 2, "'institju:t"],
  ["instruct", "vt. 教, 教育, 命令, 通知", 6, "in'strʌkt"],
  ["integral", "n. 整体, 积分, 整数；a. 固有的, 整体的, 整数的, 积分的", 9, "'intigrəl"],
  ["integrate", "vt. 综合, 使完整, 使成整体；vi. 成一体", 4, "'intigreit"],
  ["integrity", "n. 正直, 廉正, 完整", 10, "in'tegriti"],
  ["intelligence", "n. 智力, 情报, 信息", 6, "in'telidʒəns"],
  ["intense", "a. 非常的, 强烈的, 紧张的, 热情的", 8, "in'tens"],
  ["interact", "vi. 互相影响, 交互作用；n. 幕间剧, 幕间休息", 3, ".intər'ækt"],
  ["intermediate", "n. 中间物, 调停者, 中级；a. 中间的, 中级的", 9, ".intə'mi:diət"],
  ["internal", "a. 内在的, 国内的", 4, "in'tə:nəl"],
  ["interpret", "vt. 解释, 演出, 翻译, 理解；vi. 翻译, 解释", 1, "in'tə:prit"],
  ["interval", "n. 间隔, 距离, 间歇, 间隙", 6, "'intəvəl"],
  ["intervene", "vi. 插入, 调停, 干涉", 7, ".intə'vi:n"],
  ["intrinsic", "a. 本质的, 原有的, 真正的", 10, "in'trinsik"],
  ["invest", "vt. 投资, 花费, 笼罩, 授予；vi. 投资, 利用", 2, "in'vest"],
  ["investigate", "v. 调查, 审查", 4, "in'vestigeit"],
  ["invoke", "vt. 祈求, 恳求, 实行, 援引, 引起", 10, "in'vəuk"],
  ["involve", "vt. 包括, 使陷于, 潜心于, 包围", 1, "in'vɒlv"],
  ["isolate", "vt. 使隔离, 使孤立, 使绝缘；n. 隔离种群", 7, "'aisəleit"],
  ["issue", "n. 发行, 问题, 后果, 流出, 出口, 争端；vi. 发行, 流出, 造成...结果, 传下", 1, "'isju"],
  ["item", "n. 项目, 条款, 一则, 项", 2, "'aitəm"],
  ["job", "n. 工作, 零活, 职业, 事情；vi. 做零工, 打杂, 做股票经纪, 假公济私", 4, "dʒɒb"],
  ["journal", "n. 日记, 杂志, 日报", 2, "'dʒə:nəl"],
  ["justify", "vt. 替...辩护, 证明；vi. 证明合法", 3, "'dʒʌstifai"],
  ["label", "n. 标签, 称号, 商标, 标志；vt. 贴标签于, 标注", 4, "'leibl"],
  ["labour", "n. 劳动, 努力, 工作, 劳工, 分娩；vi. 劳动, 努力, 苦干", 1, "'leibə"],
  ["layer", "n. 层, 产卵鸡, 放置者；vt. 分层堆积, 压植", 3, "'leiə"],
  ["lecture", "n. 演讲, 谴责, 讲稿；vt. 演讲, 训诫, 说教", 6, "'lektʃə"],
  ["legal", "a. 法律的, 法定的, 合法的", 1, "'li:gəl"],
  ["legislate", "vi. 制定法律；vt. 用立法规定", 1, "'ledʒisleit"],
  ["levy", "n. 税款, 所征的人数, 征收；vi. 征税, 课税", 10, "'levi"],
  ["liberal", "n. 自由主义者；a. 慷慨的, 不拘泥的, 宽大的, 自由主义的", 5, "'libərəl"],
  ["licence", "n. 执照, 许可证, 特许；vt. 许可, 特许, 认可", 5, "'laisns"],
  ["likewise", "adv. 同样地, 也", 10, "'laikwaiz"],
  ["link", "n. 环, 连结物, 链接, 火把；vt. 连结, 联合, 挽住", 3, "liŋk"],
  ["locate", "vt. 找出, 设于, 位于；vi. 定居", 3, "'ləukeit"],
  ["logic", "n. 逻辑, 逻辑学, 推理的方法, 推理, 逻辑性", 5, "'lɒdʒik"],
  ["maintain", "vt. 维持, 维修, 保持, 坚持, 供养, 主张", 2, "mein'tein"],
  ["major", "n. 主修课, 成年人, 陆军少校；a. 主要的, 较多的, 大部分的, 成年的, 严重的", 1, "'meidʒə"],
  ["manipulate", "vt. 操纵, 利用, 操作, 巧妙地处理, 假造", 8, "mə'nipjuleit"],
  ["manual", "n. 手册, 指南；a. 手的, 手动的, 手工的, 体力的", 9, "'mænjuəl"],
  ["margin", "n. 页边的空白, 边缘, 界限, 余裕, 差数, 差额, 保证金；vt. 加边于, 加旁注于", 5, "'mɑ:dʒin"],
  ["mature", "a. 成熟的, 到期的, 充分考虑的；vt. 使成熟", 9, "mə'tjuə"],
  ["maximise", "vt. 把...增加到最大限度, 把...扩大到最大限度, 充分重视, 找出...的最高值", 3, "'mæksimaiz"],
  ["mechanism", "n. 机械, 机构, 结构, 机理, 技巧", 4, "'mekənizm"],
  ["media", "n. 媒体", 7, "'mi:diə"],
  ["mediate", "a. 居间的, 间接的；vt. 斡旋, 调停", 9, "'mi:dieit"],
  ["medical", "n. 医生, 体格检查；a. 医学的, 内科的, 药的", 5, "'medikl"],
  ["medium", "n. 媒体, 方法, 媒介；a. 半生熟的, 中间的", 9, "'mi:diəm"],
  ["mental", "a. 心智的, 精神病的, 心理的, 颏的；n. 精神病患者", 5, "'mentl"],
  ["method", "n. 方法, 办法, 条理, 秩序", 1, "'meθəd"],
  ["migrate", "vi. 移动, 移往, 随季节而移居", 6, "'maigreit"],
  ["military", "n. 军队；a. 军事的, 军人的, 适于战争的", 9, "'militəri"],
  ["minimal", "a. 最小的, 极微的, 最小限度的", 9, "'miniml"],
  ["minimise", "vt. 使减到最少/最小, 使降到最低限度, 使缩到最小, 极度轻视", 8, "ˈmɪnɪmaɪz"],
  ["minimum", "a. 最小的, 最低的；n. 最小值", 6, "'miniməm"],
  ["ministry", "n. 部, 内阁, 服务", 6, "'ministri"],
  ["minor", "n. 未成年人, 副修科目；a. 较小的, 二流的, 未成年的", 3, "'mainə"],
  ["mode", "n. 模态, 调式, 样式, 文体, 状态, 方式, 风尚", 7, "məud"],
  ["modify", "vt. 修正, 变更, 修饰, 缓和, 减轻；vi. 被修改", 5, "'mɒdifai"],
  ["monitor", "n. 监督器, 级长, 监听员, 班长, 监视器, 告诫物；v. 监视, 监听, 监督", 5, "'mɒnitə"],
  ["motive", "n. 动机, 目的, 主题, 基调；a. 运动的, 成为动机的", 6, "'məutiv"],
  ["mutual", "a. 相互的, 共有的", 9, "'mju:tʃuəl"],
  ["negate", "vt. 否定, 否认, 取消", 3, "ni'geit"],
  ["network", "n. 网络, 广播网, 网状物", 5, "'netwə:k"],
  ["neutral", "n. 中立者, 中立国, 非彩色, 空档；a. 中立的, 中性的, 无色的", 6, "'nju:trəl"],
  ["nevertheless", "adv. 然而, 虽然如此；conj. 然而", 6, ".nevəðə'les"],
  ["nonetheless", "conj. 然而, 尽管, 不过；adv. 不过, 仍然, 尽管如此, 然而", 10, ",nʌnðə'les"],
  ["norm", "n. 基准, 模范, 标准, 准则, 平均数", 9, "nɒ:m"],
  ["normal", "n. 常态, 标准, 正常, 普通；a. 正常的, 正规的, 标准的, 师范的, 正态的", 2, "'nɒ:ml"],
  ["notion", "n. 概念, 观念, 想法, 打算, 别致的小东西", 5, "'nəuʃən"],
  ["notwithstanding", "adv. 虽然, 尽管；prep. 尽管", 10, ".nɒtwiθ'stændiŋ"],
  ["nuclear", "a. 核子的, 原子能的, 核的, 中心的", 8, "'nju:kliə"],
  ["objective", "n. 目的, 目标, 宗旨, 宾格, 实物；a. 客观的, 如实的, 无偏见的, 宾格的", 5, "əb'dʒektiv"],
  ["obtain", "vt. 获得, 达到；vi. 流行, 得到公认", 2, "əb'tein"],
  ["obvious", "a. 明显的, 明白的, 显然的, 平淡无奇的", 4, "'ɒbviəs"],
  ["occupy", "vt. 占领, 占(时间、空间等), 住进, 担任, 使从事, 使全神贯注", 4, "'ɒkjupai"],
  ["occur", "vi. 发生, 被想到, 存在", 1, "ə'kə:"],
  ["odd", "a. 奇数的, 古怪的, 剩余的, 零散的, 各种各样的, 少量的；n. 奇特的事物, 怪人", 10, "ɒd"],
  ["offset", "n. 抵消, 把...并列, 旁系, 支管, 用胶印法印；vt. 弥补, 抵消, 胶印", 8, "'ɒ:fset"],
  ["ongoing", "a. 前进的, 进行的, 不间断的；n. 前进, 发展", 10, "'ɒngəuiŋ"],
  ["option", "n. 选择权, 挑选, 选项", 4, "'ɒpʃən"],
  ["orient", "n. 东方, 东方诸国；a. 东方的", 5, "'ɒ:riənt"],
  ["outcome", "n. 结果, 出口", 3, "'autkʌm"],
  ["output", "n. 输出, 产品, 产量", 4, "'autput"],
  ["overall", "a. 全部的, 全体的, 从头至尾的, 一切在内的；adv. 从头到尾, 总的说来", 4, "'əuvərɒ:l"],
  ["overlap", "n. 重叠, 重复, 部分的同时发生；vt. 重叠, 重复, 与...同时发生", 9, ".əuvə'læp"],
  ["overseas", "a. 海外的, 国外的；adv. 在海外, 在国外", 6, "'əuvə'si:z"],
  ["panel", "n. 嵌板, 仪表板, 专题讨论小组, 全体陪审员；vt. 嵌镶板", 10, "'pænl"],
  ["paradigm", "n. 范例, 式样, 词形变化表, 纵聚合关系语言项", 7, "'pærədaim"],
  ["paragraph", "n. 段落, 短评；vt. 将...分段, 分段落", 8, "'pærəgrɑ:f"],
  ["parallel", "n. 平行, 对比, 相匹敌之物；a. 平行的, 相似的", 4, "'pærəlel"],
  ["parameter", "n. 参变数, 参变量, 参数, 参量", 4, "pə'ræmitə"],
  ["participate", "vi. 参加, 分享, 参与, 带有；vt. 分享, 分担", 2, "pɑ:'tisipeit"],
  ["partner", "n. 合伙人, 股东, 伙伴, 伴侣；vt. 与...合伙, 组成一对", 3, "'pɑ:tnə"],
  ["passive", "a. 消极的, 被动的, 冷漠的, 顺从的, 无源的", 9, "'pæsiv"],
  ["perceive", "vt. 感觉, 认知, 理解, 意识到", 2, "pə'si:v"],
  ["percent", "n. 百分比, 百分数, 部分", 1, "pə'sent"],
  ["period", "n. 时期, 节段, 节, 句点, 学时, 周期；a. 当时特有的, 过去某段时期的", 1, "'piəriəd"],
  ["persist", "vi. 坚持, 固执, 持续, 坚称", 10, "pə'sist"],
  ["perspective", "n. 远景, 透视感, (观察问题的)视角, 透视法, 看法, 透视图；a. 透视的, 透视法的", 5, "pə'spektiv"],
  ["phase", "n. 时期, 局面, 方面, 位相, 相, 阶段；vt. 使调整相位, 使定相, 使一致, 逐步执行, 实行", 4, "feiz"],
  ["phenomenon", "n. 现象, 迹象, 表现, 奇迹, 奇才", 7, "fi'nɒminən"],
  ["philosophy", "n. 哲学, 人生观, 哲学思想, 哲理, 基本原理, 见解, 达观, 沉着", 3, "fi'lɒsəfi"],
  ["physical", "a. 身体的, 物质的, 自然的, 物理学的, 好色的；n. 体格检查", 3, "'fizikl"],
  ["plus", "prep. 加上, 加, 外加；a. 正的, 附加的", 8, "plʌs"],
  ["policy", "n. 政策, 方针, 策略, 保险单", 1, "'pɒlisi"],
  ["portion", "n. 部分, 一份, 命运, 嫁妆；vt. 分配, 给...嫁妆", 9, "'pɒ:ʃən"],
  ["pose", "n. 姿势, 姿态, 装模作样, 伪装；vi. 摆姿势, 装模作样, 假装", 10, "pəuz"],
  ["positive", "a. 肯定的, 积极的, 有把握的", 2, "'pɒzitiv"],
  ["potential", "n. 潜在性, 可能性, 潜力, 潜能, 势, 位；a. 有潜力的, 可能的, 潜在的", 2, "pə'tenʃəl"],
  ["practitioner", "n. 从业者, 开业者", 8, "præk'tiʃənə"],
  ["precede", "vt. 在...之前, 优于, 较...优先；vi. 在前面", 6, ".pri:'si:d"],
  ["precise", "a. 精确的, 严谨的, 明确的", 5, "pri'sais"],
  ["predict", "v. 预知, 预言, 预报", 4, "pri'dikt"],
  ["predominant", "a. 占主导地位的, 卓越的", 8, "pri'dɒminənt"],
  ["preliminary", "n. 初步做法, 初步措施, 预试, 预选赛；a. 初步的, 开始的, 预备的", 9, "pri'liminəri"],
  ["presume", "vt. 假定, 推测, 擅自, 意味着；vi. 擅自行动, 相信", 6, "pri'zu:m"],
  ["previous", "a. 早先的, 前面的, 过急的", 2, "'pri:viəs"],
  ["primary", "n. 最主要者, 原色；a. 主要的, 初期的, 根本的, 原始的, 首要的, 基本的", 2, "'praiməri"],
  ["prime", "n. 最佳部分, 初期, 全盛期；a. 主要的, 最初的, 根本的", 5, "praim"],
  ["principal", "n. 校长, 首长, 本金, 主犯, 资本, 委托人；a. 主要的, 最重要的, 首要的", 4, "'prinsipəl"],
  ["principle", "n. 原则, 原理, 主义", 1, "'prinsipl"],
  ["prior", "a. 更重要的, 较早的, 在先的；n. 小隐修院院长, 大隐修院副院长", 4, "'praiə"],
  ["priority", "n. 优先权, 优先", 7, "prai'ɒriti"],
  ["proceed", "vi. 继续进行, 进行, 开始, 发出, 起诉", 1, "prəu'si:d"],
  ["process", "n. 程序, 进行, 过程；vt. 加工, 使...接受处理, 对...处置, 对...起诉", 1, "'prɒses"],
  ["professional", "n. 专业人才；a. 专业的, 职业的", 4, "prə'feʃənl"],
  ["prohibit", "vt. 禁止, 阻止", 7, "prə'hibit"],
  ["project", "n. 计划, 设计, 事业；vt. 计划, 设计, 投掷, 发射, 使凸出, 放映", 4, "'prɒdʒekt"],
  ["promote", "vt. 促进, 晋升, 创办, 推销", 4, "prəu'məut"],
  ["proportion", "n. 比例, 比率, 均衡, 部分, 面积；vt. 使成比例, 使均衡", 3, "prə'pɒ:ʃən"],
  ["prospect", "n. 景色, 展望；vt. 勘探, 勘察", 8, "'prɒspekt"],
  ["protocol", "n. 草案, 礼仪, 协议；v. 拟定", 9, "'prəutəkɒl"],
  ["psychology", "n. 心理学, 心理状态", 5, "sai'kɒlədʒi"],
  ["publication", "n. 出版物, 出版, 公布", 7, ".pʌbli'keiʃən"],
  ["publish", "vt. 出版, 发行, 公开, 发表, 宣传, 公布；vi. 出版, 发行", 3, "'pʌbliʃ"],
  ["purchase", "n. 购买, 购买品, 紧握, 绞辘；vt. 购买, 赢得, 努力取得, 用滑轮起(锚等)", 2, "'pə:tʃəs"],
  ["pursue", "vt. 追赶, 追踪, 追随, 追求, 实行, 继续, 从事；vi. 追赶, 继续", 5, "pə'sju:"],
  ["qualitative", "a. 性质的, 质的, 定性的", 9, "'kwɒlitətiv"],
  ["quote", "n. 引用；vt. 引述, 举证, 报(价)", 7, "kwəut"],
  ["radical", "n. 激进分子, 词根, 基础, 根式, 根；a. 激进的, 根本的, 基本的, 根的", 8, "'rædikl"],
  ["random", "n. 随意, 随机；a. 任意的, 随便的, 胡乱的, 随机的", 8, "'rændəm"],
  ["range", "n. 排, 行, 山脉, 范围, 行列, 射程；vt. 排列, 归类于, 使并列, 放牧", 2, "'reindʒ"],
  ["ratio", "n. 比, 比率", 5, "'reiʃəu"],
  ["rational", "a. 理性的, 合理的；n. 有理数", 6, "'ræʃənl"],
  ["react", "vi. 起反应, 起作用, 反攻", 3, "ri'ækt"],
  ["recover", "vt. 重新获得, 恢复, 复原, 拯救；vi. 痊愈, 复原, 胜诉", 6, "ri'kʌvə"],
  ["refine", "vt. 精炼, 净化, 使优雅, 使精炼；vi. 被精炼, 被净化", 9, "ri'fain"],
  ["regime", "n. 政权, 当权期间, 政体, 社会制度, 体制, 情态", 4, "rei'ʒi:m"],
  ["region", "n. 区域, 地带, 地区, 领域, 范围, 区", 2, "'ri:dʒən"],
  ["register", "n. 寄存器, 记录, 登记簿, 注册；vt. 记录, 注册, 提示, 表达, 把...挂号", 3, "'redʒistə"],
  ["regulate", "vt. 管理, 控制, 调节, 调整, 校准", 2, "'regjuleit"],
  ["reinforce", "vt. 加强, 增援, 补充；vi. 求援, 得到增援", 8, ".ri:in'fɒ:s"],
  ["reject", "n. 被拒之人, 被弃之物, 不合格品, 次品；vt. 拒绝, 抵制, 否决, 驳回, 丢弃, 呕出", 5, "ri'dʒekt"],
  ["relax", "vi. 放松, 松懈, 松弛, 变从容, 休息, 休养；vt. 使松弛, 缓和, 使松懈, 使休息", 9, "ri'læks"],
  ["release", "n. 释放, 发泄, 豁免, 发行, 释放证书；vt. 释放, 解除, 放松, 豁免, 免除, 发布, 放弃, 让与", 7, "ri'li:s"],
  ["relevant", "a. 有关联的, 有关系的, 适当的, 相应的", 2, "'relivənt"],
  ["reluctance", "n. 不情愿, 勉强", 10, "ri'lʌktəns"],
  ["rely", "vi. 信赖, 依赖, 信任", 3, "ri'lai"],
  ["remove", "vt. 移动, 调动, 除去, 迁移, 开除, 移交；vi. 迁移, 移动, 搬家", 3, "ri'mu:v"],
  ["require", "vt. 需要, 命令, 要求", 1, "ri'kwaiə"],
  ["research", "n. 研究, 调查, 考察；vi. 研究, 调查", 1, "ri'sə:tʃ"],
  ["reside", "vi. 住, 居留, 属于", 2, "ri'zaid"],
  ["resolve", "vi. 决定, 分解, 决心；vt. 使分解, 解析, 解决, 消除, 决心", 4, "ri'zɒlv"],
  ["resource", "n. 资源, 财力, 办法, 策略, 急智, 消遣", 2, "ri'sɒ:s"],
  ["respond", "vt. 以...回答；vi. 回答, 响应, 回报, 有反应, 承担责任", 1, "ri'spɒnd"],
  ["restore", "vt. 回复, 恢复, 归还, 修补, 修复；vt. 还原", 8, "ri'stɒ:"],
  ["restrain", "vt. 抑制, 阻止, 束缚", 9, "ri'strein"],
  ["restrict", "vt. 限制, 限定, 约束", 2, "ri'strikt"],
  ["retain", "vt. 保持, 保有, 留住, 记得, 付定金聘请", 4, "ri'tein"],
  ["reveal", "vt. 露出, 显示, 透露, 揭露, 泄露, (神)启示；n. 窗侧, 门侧", 6, "ri'vi:l"],
  ["revenue", "n. 收入, 岁入, 税收, 税务局", 5, "'revinju:"],
  ["reverse", "n. 相反, 背面, 倒退, 挫折, 失败；a. 反面的, 相反的, 反向的, 颠倒的", 7, "ri'və:s"],
  ["revise", "n. 校订, 修正, 改样；vt. 校订, 修正, 校正", 8, "ri'vaiz"],
  ["revolution", "n. 革命, 大变革, 旋转, 转数, 循环", 9, ".revə'lu:ʃən"],
  ["rigid", "a. 坚硬的, 刚性的, 严格的, 精密的, 刻板的", 9, "'ridʒid"],
  ["role", "n. 角色, 职责, 任务", 1, "rəul"],
  ["route", "n. 路径, 途径, 路线；vt. 确定路线, 按规定路线发送", 9, "ru:t"],
  ["scenario", "n. 剧本提纲, 情节, 剧本, 方案, 事态", 9, "si'nɑ:riəu"],
  ["schedule", "n. 时间表, 一览表, 计划表, 议事日程；vt. 预定, 编制目录, 制...表, 安排", 8, "'skedʒuəl"],
  ["scheme", "n. 方案, 计划, 组合, 系统, 图解, 诡计, 阴谋；v. 计划, 设计, 图谋, 策划", 3, "ski:m"],
  ["scope", "n. 范围, 机会, 广度, 眼界, 观察仪器, 导弹射程", 6, "skəup"],
  ["section", "n. 区段, 部分, 区域, 节, 截面, 处, 科, 区, 扇区；vt. 把...分段, 把...切片", 1, "'sekʃən"],
  ["sector", "n. 扇形, 部门, 部分, 函数尺, 象限仪, 段, 区段；vt. 把...分成扇形", 1, "'sektə"],
  ["secure", "a. 无虑的, 安心的, 安全的, 可靠的, 保险的；vt. 固定, 获得, 保证, 使安全, 掩护, 招致", 2, "si'kjuə"],
  ["seek", "vt. 寻求, 寻找, 探索, 追求, 搜索, 请求；vi. 寻找, 搜索", 2, "si:k"],
  ["select", "a. 挑选出来的, 极好的；v. 选择, 挑选", 2, "si'lekt"],
  ["sequence", "n. 序列, 续发事件, 顺序, 连续；vt. 按顺序排好", 3, "'si:kwəns"],
  ["series", "n. 串联, 序列, 连续, 系列, 丛书, 套, 级数, 组", 4, "'siəri:z"],
  ["sex", "n. 性别, 性欲；vt. 区别...的性别, 引起...的性欲", 3, "seks"],
  ["shift", "n. 变化, 移动, 轮班, 手段, 应急办法, 移位；vt. 替换, 转移, 改变, 推卸, 变速", 3, "ʃift"],
  ["significant", "a. 重要的, 有效的, 有含义的, 暗示的, 值得注意的", 1, "sig'nifikənt"],
  ["similar", "a. 相似的, 类似的；n. 相似的东西", 1, "'similə"],
  ["simulate", "vt. 模拟, 假装, 模仿", 7, "'simjuleit"],
  ["site", "n. 位置, 场所, 地点；vt. 给...择址", 2, "sait"],
  ["so-called", "a. 所谓的, 号称的", 10, "ˌsəʊˈkɔːld"],
  ["sole", "n. 脚掌, 鞋底, 底部；a. 唯一的, 仅有的, 单独的, 独身的", 7, "səul"],
  ["somewhat", "n. 某物, 几分；adv. 多少, 几分", 7, "'sʌmhwɒt"],
  ["source", "n. 来源, 水源, 根源, 原始资料, 源", 1, "sɒ:s"],
  ["specific", "n. 特效药, 特性；a. 特殊的, 明确的, 具有特效的, 特定地, 具体地", 1, "spi'sifik"],
  ["specify", "vt. 详列, 指定, 说明", 3, "'spesifai"],
  ["sphere", "n. 球, 球面, 球体, 天体, 地球仪, 范围；vt. 包围, 使成球体, 放入球内", 9, "sfiə"],
  ["stable", "n. 马房, 牛棚；a. 稳定的, 安定的, 坚固的, 坚定的", 5, "'steibl"],
  ["statistic", "n. 统计量；a. 统计的, 统计学的", 4, "stə'tistik"],
  ["status", "n. 状态, 情形, 地位, 要人身份", 4, "'steitəs"],
  ["straightforward", "a. 笔直的, 率直的, 明确的, 简单的, 直接的", 10, "streit'fɒ:wəd"],
  ["strategy", "n. 战略, 策略", 2, "'strætidʒi"],
  ["stress", "n. 压力, 紧迫, 强调, 重音, 重点, 应力；vt. 加压力于, 着重, 重读", 4, "stres"],
  ["structure", "n. 结构, 构造, 建筑物；vt. 构成, 组织", 1, "'strʌktʃə"],
  ["style", "n. 风格, 时尚, 文体, 风度, 字体, 类型；vt. 称呼, (根据新款式)设计, 使合潮流", 5, "stail"],
  ["submit", "vt. 使服从, 使受到, 委托, 提交, 认为；vi. 屈服, 服从", 7, "səb'mit"],
  ["subordinate", "n. 属下, 附属物；a. 下级的, 次要的, 附属的", 9, "sə'bɒ:dnit"],
  ["subsequent", "a. 后来的, 接下去的", 4, "'sʌbsikwənt"],
  ["subsidy", "n. 补助金, 津贴", 6, "'sʌbsidi"],
  ["substitute", "n. 代理, 代理人, 代用品, 代替者, 代替物；vt. 代替", 5, "'sʌbstitju:t"],
  ["successor", "n. 继承者, 接任者", 7, "sək'sesə"],
  ["sufficient", "a. 充分的, 足够的", 3, "sə'fiʃənt"],
  ["sum", "n. 总数, 总和, 金额, 概要, 顶点；vt. 总计, 概括", 4, "sʌm"],
  ["summary", "n. 摘要, 概要；a. 摘要的, 简略的", 4, "'sʌməri"],
  ["supplement", "n. 补充物, 增刊, 补充, 补遗, 补编, 附录, 补角；vt. 补充, 增补", 9, "'sʌplimənt"],
  ["survey", "n. 纵览, 视察, 测量, 俯瞰, 调查；vt. 审视, 视察, 俯瞰, 通盘考虑", 2, "sə'vei"],
  ["survive", "vt. 比...活得长, 生存, 生还, 幸免于；vi. 活下来, 幸存", 7, "sə'vaiv"],
  ["suspend", "vt. 悬, 吊, 使悬浮, 暂停, 中止, 推迟；vi. 暂停, 中止, 悬浮, 停止偿付债务", 9, "sə'spend"],
  ["sustain", "vt. 承受, 支持, 供养, 继续, 忍受, 蒙受, 证实, 准许", 5, "sə'stein"],
  ["symbol", "n. 符号, 象征, 代号, 信条", 5, "'simbl"],
  ["tape", "n. 带子, 录音带, 磁带, 窄带, 卷尺；vt. 以带子绑起, 测量, 录音", 6, "teip"],
  ["target", "n. 目标, 靶子, 指标；vt. 对准, 订指标", 5, "'tɑ:git"],
  ["task", "n. 工作, 任务, 作业, 困难的工作；vt. 派给...工作, 使辛劳", 3, "tɑ:sk"],
  ["team", "n. 队, 组；vt. 把马(牛)套在同一辆车上, 把...编成一组", 9, "ti:m"],
  ["technical", "a. 技术上的, 专门的, 工业的, 严格根据法律的", 3, "'teknikl"],
  ["technique", "n. 技巧, 技术, 方法", 3, "tek'ni:k"],
  ["technology", "n. 技术, 工业技术, 术语", 3, "tek'nɒlədʒi"],
  ["temporary", "a. 暂时的, 临时的；n. 临时工, 临时雇员", 9, "'tempərəri"],
  ["tense", "a. 紧张的, 拉紧的；v. (使)紧张, (使)拉紧", 8, "tens"],
  ["terminate", "a. 有结尾的, (可)结束的；vi. 结束, 终止, 满期", 8, "'tə:mineit"],
  ["text", "n. 文本, 正文, 课文, 主题, 圣经文句, 乐谱", 2, "tekst"],
  ["theme", "n. 主题, 话题, 题目", 8, "θi:m"],
  ["theory", "n. 理论, 学说, 原理, 意见, 推测", 1, "'θiəri"],
  ["thereby", "adv. 因此", 8, "'ðeəbai"],
  ["thesis", "n. 论题, 论文", 7, "'θi:sis"],
  ["topic", "n. 主题, 论题, 话题", 7, "'tɒpik"],
  ["trace", "n. 痕迹, 踪迹, 微量, 迹线, 缰绳；vt. 追踪, 回溯, 描绘", 6, "treis"],
  ["tradition", "n. 传说, 传统, 交付", 2, "trə'diʃən"],
  ["transfer", "n. 迁移, 移动, 传递, 转让, 转移, 过户, 汇兑, 换车；vt. 使转移, 调转, 调任, 改变, 传递, 转让", 2, "træns'fə:"],
  ["transform", "vt. 使转换, 改变, 改造, 使...变形；vi. 改变, 转化, 变换", 6, "træns'fɒ:m"],
  ["transit", "n. 经过, 通行, 运输, 运输线, 转变；vt. 运送, 使通过, 经过", 5, "'trænsit"],
  ["transmit", "vt. 传输, 传染, 传达, 遗传, 发射, 传播；vi. 发射信号, 留传下来", 7, "træns'mit"],
  ["transport", "n. 运输, 运输工具, 激动, 狂喜, 流放犯；vt. 传送, 运输, 流放", 6, "træns'pɒ:t"],
  ["trend", "n. 趋势, 倾向, 走向；vi. 倾向, 转向", 5, "trend"],
  ["trigger", "n. 触发器, 扳机；vt. 触发, 发射, 引起", 9, "'trigə"],
  ["ultimate", "n. 终极, 根本, 顶点, 基本原则；a. 终极的, 根本的, 极限的, 最远的, 最后的, 最大的", 7, "'ʌltimit"],
  ["undergo", "vt. 遭受, 经历, 忍受", 10, ".ʌndə'gəu"],
  ["underlie", "vt. 位于...之下, 成为...的基础", 6, ".ʌndə'lai"],
  ["undertake", "vt. 试图, 从事, 保证, 承担, 同意, 接受", 4, ".ʌndə'teik"],
  ["uniform", "n. 制服；a. 统一的, 一律的, 始终如一的", 8, "'ju:nifɒ:m"],
  ["unify", "v. 统一, 使成一体", 9, "'ju:nifai"],
  ["unique", "a. 独一无二的, 独特的, 稀罕的", 7, "ju:'ni:k"],
  ["utilise", "vt. 利用, 运用, 使用", 6, "'ju:tilaiz"],
  ["valid", "a. 有确实根据的, 有法律效力的, 正当的, 正确的", 3, "'vælid"],
  ["vary", "vt. 改变, 使多样化；vi. 变化, 有不同, 违反", 1, "'veəri"],
  ["vehicle", "n. 交通工具, 车辆, 传播媒介", 8, "'vi:ikl"],
  ["version", "n. 一种描述, 版本, 译文", 5, "'və:ʒən"],
  ["via", "prep. 经由, 经过, 通过", 8, "vaiə"],
  ["violate", "vt. 违犯, 亵渎, 违反, 侵犯, 妨碍", 9, "'vaiəleit"],
  ["virtual", "a. 实际上起作用的, 虚的, 实质的, 有效的, 事实上生效的", 8, "'və:tʃuəl"],
  ["visible", "a. 看得见的, 明显的, 显然的；n. 可见物", 7, "'vizəbl"],
  ["vision", "n. 视觉, 眼光, 视力, 幻想；vt. 梦见, 想象, 显示", 9, "'viʒən"],
  ["visual", "a. 视觉的", 8, "'viʒuəl"],
  ["volume", "n. 册, 卷, 体积, 容量, 大量, 许多, 份量, 音量；vi. 成团卷起", 3, "'vɒljum"],
  ["voluntary", "a. 自动的, 自愿的, 故意的, 志愿的, 自发的；n. 自愿行动, 志愿者, 自由调", 7, "'vɒləntəri"],
  ["welfare", "n. 福利, 安宁, 幸福, 福利事业；a. 福利的", 5, "'welfeə"],
  ["whereas", "conj. 然而, 鉴于", 5, "hweər'æz"],
  ["whereby", "adv. 靠什么, 如何, 为何, 靠那个, 因此, 由此", 10, "(h)weə'bai"],
  ["widespread", "a. 充分伸展的, 广布的, 普及的, 流传广的", 8, "'waidspred"],
] as const;
