// 570 headwords from Averil Coxhead's Academic Word List (AWL).
// Definitions are concise offline glosses based on WordNet.
export type VocabularyEntry = readonly [word: string, meaning: string, sublist: number];

export const WORDS: readonly VocabularyEntry[] = [
  ["abandon", "the trait of lacking restraint or control; reckless freedom from inhibition or worry", 8],
  ["abstract", "a concept or idea not associated with any specific instance", 6],
  ["academy", "a secondary school (usually private)", 5],
  ["access", "the right to enter", 4],
  ["accommodate", "be agreeable or acceptable to", 9],
  ["accompany", "be present or associated with an event or entity", 8],
  ["accumulate", "get or gather together", 8],
  ["accurate", "conforming exactly or almost exactly to fact or to a standard or performing with total accuracy", 6],
  ["achieve", "to gain with effort", 2],
  ["acknowledge", "declare to be true or admit the existence or reality or truth of", 6],
  ["acquire", "come into the possession of something concrete or abstract", 2],
  ["adapt", "make fit for, or change to suit a new purpose", 7],
  ["adequate", "having the requisite qualities or resources to meet a task", 4],
  ["adjacent", "nearest in space or position; immediately adjoining without intervening space", 10],
  ["adjust", "alter or regulate so as to achieve accuracy or conform to a standard", 5],
  ["administration", "a method of tending to or managing the affairs of a some group of people (especially the group's business affairs)", 2],
  ["adult", "a fully developed person from maturity onward", 7],
  ["advocate", "a person who pleads for a cause or propounds an idea", 7],
  ["affect", "the conscious subjective aspect of feeling or emotion", 2],
  ["aggregate", "the whole amount", 6],
  ["aid", "a resource", 7],
  ["albeit", "an academic word from frequency sublist 10", 10],
  ["allocate", "distribute according to a plan or set apart for a special purpose", 6],
  ["alter", "cause to change; make different; cause a transformation", 5],
  ["alternative", "one of a number of things from which only one can be chosen", 3],
  ["ambiguous", "open to two or more interpretations; or of uncertain nature or significance; or (often) intended to mislead", 8],
  ["amend", "make amendments to", 5],
  ["analogy", "an inference that if things agree in some respects they probably agree in others", 9],
  ["analyse", "examine something carefully and in detail", 1],
  ["annual", "(botany) a plant that completes its entire life cycle within the space of a year", 4],
  ["anticipate", "regard something as probable or likely", 9],
  ["apparent", "clearly revealed to the mind or the senses or judgment", 4],
  ["append", "add to the very end", 8],
  ["appreciate", "recognize with gratitude; be grateful for", 8],
  ["approach", "ideas or actions intended to deal with a problem or situation", 1],
  ["appropriate", "give or assign a resource to a particular person or cause", 2],
  ["approximate", "be close or similar", 4],
  ["arbitrary", "based on or subject to individual discretion or preference or sometimes impulse or caprice", 8],
  ["area", "a subject, activity, or field of study", 1],
  ["aspect", "a distinct feature or element in a problem", 2],
  ["assemble", "create by putting components or members together", 10],
  ["assess", "evaluate or estimate the nature, quality, ability, extent, or significance of", 1],
  ["assign", "give an assignment to (a person) to a post, or assign a task to (a person)", 6],
  ["assist", "the activity of contributing to the fulfillment of a need or furtherance of an effort or purpose", 2],
  ["assume", "take to be the case or to be true; accept without verification or proof", 1],
  ["assure", "make certain of", 9],
  ["attach", "cause to be attached", 6],
  ["attain", "to gain with effort", 9],
  ["attitude", "a complex mental state involving beliefs and feelings and values and dispositions to act in certain ways", 4],
  ["attribute", "a construct whereby objects or individuals can be distinguished", 4],
  ["author", "writes (books or stories or articles or the like) professionally (for pay)", 6],
  ["authority", "the power or right to give orders or make decisions", 1],
  ["automate", "make automatic or control or operate automatically", 8],
  ["available", "obtainable or accessible and ready for use or service", 1],
  ["aware", "(sometimes followed by `of') having or showing knowledge or understanding or realization or perception", 5],
  ["behalf", "as the agent of or on someone's part (usually expressed as  rather than )", 9],
  ["benefit", "financial assistance in time of need", 1],
  ["bias", "a partiality that prevents objective consideration of an issue or situation", 8],
  ["bond", "an electrical force linking atoms", 6],
  ["brief", "a document stating the facts and points of law of a client's case", 6],
  ["bulk", "the property resulting from being or relating to the greater in number of two parts; the main part", 9],
  ["capable", "(usually followed by `of') having capacity or ability", 6],
  ["capacity", "capability to perform or produce", 5],
  ["category", "a collection of things sharing a common attribute", 2],
  ["cease", "(`cease' is a noun only in the phrase `without cease') end", 9],
  ["challenge", "a demanding or stimulating situation", 5],
  ["channel", "a path over which electrical signals can pass", 7],
  ["chapter", "a subdivision of a written work; usually numbered and titled", 2],
  ["chart", "a visual display of information", 8],
  ["chemical", "material produced by or used in a reaction involving changes in atoms or molecules", 7],
  ["circumstance", "a condition that accompanies or influences some event or activity", 3],
  ["cite", "a short note recognizing a source of information or of a quoted passage", 6],
  ["civil", "applying to ordinary citizens as contrasted with the military", 4],
  ["clarify", "make clear and (more) comprehensible", 8],
  ["classic", "a creation of the highest excellence", 7],
  ["clause", "(grammar) an expression including a subject and predicate but not constituting a complete sentence", 5],
  ["code", "a set of rules or principles or laws (especially written ones)", 4],
  ["coherent", "marked by an orderly, logical, and aesthetically consistent relation of parts", 9],
  ["coincide", "go with, fall together", 9],
  ["collapse", "an abrupt failure of function or complete physical exhaustion", 10],
  ["colleague", "an associate that one works with", 10],
  ["commence", "take the first step or steps in carrying out an action", 9],
  ["comment", "a statement that expresses a personal opinion or belief or adds information", 3],
  ["commission", "a special group delegated to consider some matter;  - Milton Berle", 2],
  ["commit", "perform an act, usually with a negative connotation", 4],
  ["commodity", "articles of commerce", 8],
  ["communicate", "transmit information", 4],
  ["community", "a group of people living in a particular local area", 2],
  ["compatible", "able to exist and perform in harmonious or agreeable combination", 9],
  ["compensate", "adjust for", 3],
  ["compile", "get or gather together", 10],
  ["complement", "a word or phrase used to complete a grammatical construction", 8],
  ["complex", "a conceptual whole made up of complicated and related parts", 2],
  ["component", "an abstract part of something", 3],
  ["compound", "a whole formed by a union of two or more elements or parts", 5],
  ["comprehensive", "an intensive examination testing a student's proficiency in some special field of knowledge", 7],
  ["comprise", "be composed of", 7],
  ["compute", "make a mathematical calculation or computation", 2],
  ["conceive", "have the idea for", 10],
  ["concentrate", "the desired mineral that is left after impurities have been removed from mined ore", 4],
  ["concept", "an abstract or general idea inferred or derived from specific instances", 1],
  ["conclude", "decide by reasoning; draw or come to a conclusion", 2],
  ["concurrent", "occurring or operating at the same time", 9],
  ["conduct", "manner of acting or controlling yourself", 2],
  ["confer", "have a conference in order to talk something over", 4],
  ["confine", "place limits on (extent or access)", 9],
  ["confirm", "establish or strengthen as with new evidence or facts", 7],
  ["conflict", "an open clash between two opposing groups (or individuals); --Thomas Paine", 5],
  ["conform", "be similar, be in line with", 8],
  ["consent", "permission to do something", 3],
  ["consequent", "following or accompanying as a consequence", 2],
  ["considerable", "large or relatively large in number or amount or extent or degree", 3],
  ["consist", "originate (in)", 1],
  ["constant", "a quantity that does not vary", 3],
  ["constitute", "form or compose", 1],
  ["constrain", "hold back", 3],
  ["construct", "an abstract or general idea inferred or derived from specific instances", 2],
  ["consult", "get or ask advice from", 5],
  ["consume", "eat immoderately", 2],
  ["contact", "close interaction", 5],
  ["contemporary", "a person of nearly the same age as another", 8],
  ["context", "discourse that surrounds a language unit and helps to determine its interpretation", 1],
  ["contract", "a binding agreement between two or more persons that is enforceable by law", 1],
  ["contradict", "be in contradiction with", 8],
  ["contrary", "a relation of direct opposition", 7],
  ["contrast", "the opposition or dissimilarity of things that are compared; ,", 4],
  ["contribute", "bestow a quality on", 3],
  ["controversy", "a contentious speech act; a dispute where there is strong disagreement", 9],
  ["convene", "meet formally", 3],
  ["converse", "a proposition obtained by conversion", 9],
  ["convert", "a person who has been converted to another religious or political belief", 7],
  ["convince", "make (someone) agree, understand, or realize the truth or validity of something", 10],
  ["cooperate", "work together on a common enterprise of project", 6],
  ["coordinate", "a number that identifies a position relative to an axis", 3],
  ["core", "a small group of indispensable persons or things", 3],
  ["corporate", "of or belonging to a corporation", 3],
  ["correspond", "be compatible, similar or consistent; coincide in their characteristics", 3],
  ["couple", "a pair who associate with one another", 7],
  ["create", "make or cause to be or to become", 1],
  ["credit", "approval", 2],
  ["criteria", "a basis for comparison; a reference point against which other things can be evaluated", 3],
  ["crucial", "of extreme importance; vital to the resolution of a crisis", 8],
  ["culture", "a particular society at a particular time and place", 2],
  ["currency", "the metal or paper medium of exchange that is presently used", 8],
  ["cycle", "an interval during which a recurring sequence of events occurs", 4],
  ["data", "a collection of facts from which conclusions may be drawn", 1],
  ["debate", "a discussion in which reasons are advanced for and against some proposition or proposal", 4],
  ["decade", "a period of 10 years", 7],
  ["decline", "change toward something smaller or lower", 5],
  ["deduce", "reason by deduction; establish by deduction", 3],
  ["define", "determine the essential quality of", 1],
  ["definite", "precise; explicit and clearly defined", 7],
  ["demonstrate", "give an exhibition of to an interested audience", 3],
  ["denote", "be a sign or indication of", 8],
  ["deny", "declare untrue; contradict", 7],
  ["depress", "lower someone's spirits; make downhearted", 10],
  ["derive", "reason by deduction; establish by deduction", 1],
  ["design", "the act of working out the form of something (as by making a sketch or outline or plan)", 2],
  ["despite", "lack of respect accompanied by a feeling of intense dislike", 4],
  ["detect", "discover or determine the existence, presence, or fact of", 8],
  ["deviate", "a person whose behavior deviates from what is acceptable especially in sexual behavior", 8],
  ["device", "an instrumentality invented for a particular purpose", 9],
  ["devote", "give entirely to a specific person, activity, or cause", 9],
  ["differentiate", "mark as different", 7],
  ["dimension", "the magnitude of something in a particular direction (especially length or width or height)", 4],
  ["diminish", "decrease in size, extent, or range", 9],
  ["discrete", "constituting a separate entity or part", 5],
  ["discriminate", "recognize or perceive the difference", 6],
  ["displace", "cause to move, usually with force or pressure", 8],
  ["display", "something intended to communicate a particular impression", 6],
  ["dispose", "give, sell, or transfer to another", 7],
  ["distinct", "(often followed by `from') not alike; different in nature or quality", 2],
  ["distort", "make false by mutilation or addition; as of a message or story", 9],
  ["distribute", "administer or bestow, as in small portions", 1],
  ["diverse", "many and different", 6],
  ["document", "writing that provides information (especially information of an official nature)", 3],
  ["domain", "a particular environment or walk of life", 6],
  ["domestic", "a servant who is paid to perform menial tasks around the household", 4],
  ["dominate", "be larger in number, quantity, power, status or importance", 3],
  ["draft", "a document ordering the payment of money; drawn by one person or bank on another", 5],
  ["drama", "a dramatic work intended for performance by actors on a stage", 8],
  ["duration", "the period of time during which something continues", 9],
  ["dynamic", "an efficient incentive", 7],
  ["economy", "the system of production and distribution and consumption", 1],
  ["edit", "prepare for publication or presentation by correcting, revising, or adapting", 6],
  ["element", "an abstract part of something", 2],
  ["eliminate", "terminate, end, or take out", 7],
  ["emerge", "come out into view, as from concealment", 4],
  ["emphasis", "special importance or significance", 3],
  ["empirical", "derived from experiment and observation rather than theory", 7],
  ["enable", "render capable or able for some task", 5],
  ["encounter", "a minor short-term fight", 10],
  ["energy", "(physics) a thermodynamic quantity equivalent to the capacity of a physical system to do work; the units of energy are joules or ergs", 5],
  ["enforce", "ensure observance of laws and rules", 5],
  ["enhance", "increase", 6],
  ["enormous", "extraordinarily large in size or extent or amount or power or degree; ; ; ; - Walter Lippman", 10],
  ["ensure", "make certain of", 3],
  ["entity", "that which is perceived or known or inferred to have its own distinct existence (living or nonliving)", 5],
  ["environment", "the totality of surrounding conditions", 1],
  ["equate", "consider or describe as similar, equal, or analogous", 2],
  ["equip", "provide with (something) usually for a specific purpose", 7],
  ["equivalent", "a person or thing equal to another in value or measure or force or effect or significance etc", 5],
  ["erode", "become ground down or deteriorate", 9],
  ["error", "a wrong action attributable to bad judgment or ignorance or inattention", 4],
  ["establish", "set up or found", 1],
  ["estate", "everything you own; all of your assets (whether real property or personal property) and liabilities", 6],
  ["estimate", "an approximate calculation of quantity or degree or worth", 1],
  ["ethic", "the principles of right and wrong that are accepted by an individual or a social group", 9],
  ["ethnic", "a person who is a member of an ethnic group", 4],
  ["evaluate", "evaluate or estimate the nature, quality, ability, extent, or significance of", 2],
  ["eventual", "expected to follow in the indefinite future from causes already operating", 8],
  ["evident", "clearly revealed to the mind or the senses or judgment", 1],
  ["evolve", "work out", 5],
  ["exceed", "be greater in scope or size than some standard", 6],
  ["exclude", "prevent from being included or considered or accepted", 3],
  ["exhibit", "an object or statement produced before a court of law and referred to while giving evidence", 8],
  ["expand", "extend in one or more directions", 5],
  ["expert", "a person with special knowledge or ability who performs skillfully", 6],
  ["explicit", "precisely and clearly expressed or readily observable; leaving nothing to implication", 6],
  ["exploit", "a notable achievement", 8],
  ["export", "commodities (goods or services) sold to a foreign country", 1],
  ["expose", "the exposure of an impostor or a fraud", 5],
  ["external", "outward features", 5],
  ["extract", "a solution obtained by steeping or soaking a substance (usually in water)", 7],
  ["facilitate", "make easier", 5],
  ["factor", "anything that contributes causally to a result", 1],
  ["feature", "a prominent attribute or aspect of something", 2],
  ["federal", "a member of the Union Army during the American Civil War", 6],
  ["fee", "a fixed charge for a privilege or for professional services", 6],
  ["file", "a set of related records (either written or electronic) kept together", 7],
  ["final", "the final match between the winners of all previous matches in an elimination tournament", 2],
  ["finance", "the commercial activity of providing funds and capital", 1],
  ["finite", "bounded or limited in magnitude or spatial or temporal extent", 7],
  ["flexible", "capable of being changed", 6],
  ["fluctuate", "cause to fluctuate or move in a wavelike pattern", 8],
  ["focus", "the concentration of attention or energy on something", 2],
  ["format", "the organization of information according to preset specifications (usually for computer processing)", 9],
  ["formula", "a group of symbols that make a mathematical statement", 1],
  ["forthcoming", "at ease in talking to others", 10],
  ["foundation", "the basis on which something is grounded", 7],
  ["found", "food and lodging provided in addition to money", 9],
  ["framework", "a hypothetical description of a complex entity or process", 3],
  ["function", "(mathematics) a mathematical relation such that each element of a given set (the domain of the function) is associated with an element of another set (the range of the function)", 1],
  ["fund", "a reserve of money set aside for some purpose", 3],
  ["fundamental", "any factor that could be considered important to the understanding of a particular business", 5],
  ["furthermore", "in addition", 6],
  ["gender", "a grammatical category in inflected languages governing the agreement between nouns and pronouns and adjectives; in some languages it is quite arbitrary but in Indo-European languages it is usually based on sex or animateness", 6],
  ["generate", "bring into existence", 5],
  ["generation", "all the people living at the same time or of approximately the same age", 5],
  ["globe", "the 3rd planet from the sun; the planet we live on", 7],
  ["goal", "the state of affairs that a plan is intended to achieve and that (when achieved) terminates behavior intended to achieve it", 4],
  ["grade", "a body of students who are taught together", 7],
  ["grant", "any monetary aid", 4],
  ["guarantee", "a written assurance that some product or service will be provided or will meet certain specifications", 7],
  ["guideline", "a light line that is used in lettering to help align the letters", 8],
  ["hence", "(used to introduce a logical conclusion) from that fact or reason or as a result", 4],
  ["hierarchy", "a series of ordered groupings of people or things within a system", 7],
  ["highlight", "the most interesting or memorable part", 8],
  ["hypothesis", "a proposal intended to explain certain facts or observations", 4],
  ["identical", "exactly alike; incapable of being perceived as different", 7],
  ["identify", "recognize as being; establish the identity of someone or something", 1],
  ["ideology", "an orientation that characterizes the thinking of a group or nation", 7],
  ["ignorance", "the lack of knowledge or education", 6],
  ["illustrate", "clarify by giving an example of", 3],
  ["image", "an iconic mental representation", 5],
  ["immigrate", "migrate to a new environment", 3],
  ["impact", "the striking of one body against another", 2],
  ["implement", "instrumentation (a piece of equipment or tool) used to effect an end", 4],
  ["implicate", "bring into intimate and incriminating connection", 4],
  ["implicit", "implied though not directly expressed; inherent in the nature of something", 8],
  ["imply", "express or state indirectly", 3],
  ["impose", "compel to behave in a certain way", 4],
  ["incentive", "a positive motivational influence", 6],
  ["incidence", "the relative frequency of occurrence of something", 6],
  ["incline", "an elevated geological formation", 10],
  ["income", "the financial gain (earned or unearned) accruing over a given period of time", 1],
  ["incorporate", "make into a whole or make part of a whole", 6],
  ["index", "a numerical scale used to compare variables with one another or with some reference number", 6],
  ["indicate", "be a signal for or a symptom of", 1],
  ["individual", "a human being", 1],
  ["induce", "cause to arise", 8],
  ["inevitable", "an unavoidable event", 8],
  ["infer", "reason by deduction; establish by deduction", 7],
  ["infrastructure", "the basic structure or features of a system or organization", 8],
  ["inherent", "existing as an essential constituent or characteristic", 9],
  ["inhibit", "to put down by force or authority", 6],
  ["initial", "the first letter of a word (especially a person's name)", 3],
  ["initiate", "someone new to a field or activity", 6],
  ["injure", "cause injuries or bodily harm to", 2],
  ["innovate", "bring something new to an environment", 7],
  ["input", "signal going into an electronic system", 6],
  ["insert", "a folded section placed between the leaves of another publication", 7],
  ["insight", "clear or deep perception of a situation", 9],
  ["inspect", "look over carefully", 8],
  ["instance", "an occurrence of something", 3],
  ["institute", "an association organized to promote art or science or education", 2],
  ["instruct", "impart skills or knowledge to", 6],
  ["integral", "the result of a mathematical integration; F(x) is the integral of f(x) if dF/dx = f(x)", 9],
  ["integrate", "make into a whole or make part of a whole", 4],
  ["integrity", "an undivided or unbroken completeness or totality with nothing wanting", 10],
  ["intelligence", "the ability to comprehend; to understand and profit from experience", 6],
  ["intense", "possessing or displaying a distinctive feature to a heightened degree", 8],
  ["interact", "act together or towards others or with others", 3],
  ["intermediate", "a substance formed during a chemical process before the desired product is obtained", 9],
  ["internal", "happening or arising or located within some limits or especially surface", 4],
  ["interpret", "make sense of; assign a meaning to", 1],
  ["interval", "a definite length of time marked off by two instants", 6],
  ["intervene", "get involved, so as to alter or hinder an action, or through force or threat of force", 7],
  ["intrinsic", "belonging to a thing by its very nature; - John Dewey", 10],
  ["invest", "make an investment", 2],
  ["investigate", "investigate scientifically", 4],
  ["invoke", "summon into action or bring into existence, often as if by magic", 10],
  ["involve", "connect closely and often incriminatingly", 1],
  ["isolate", "place or set apart", 7],
  ["issue", "an important topic or problem for discussion", 1],
  ["item", "a distinct part that can be specified separately in a group of things that could be enumerated on a list", 2],
  ["job", "the principal activity in your life that you do to earn money", 4],
  ["journal", "a daily written record of (usually personal) experiences and observations", 2],
  ["justify", "show to be reasonable or provide adequate ground for", 3],
  ["label", "a brief description given for purposes of identification", 4],
  ["labour", "a social class comprising those who do manual labor or work for wages", 1],
  ["layer", "single thickness of usually some homogeneous substance", 3],
  ["lecture", "a speech that is open to the public", 6],
  ["legal", "established by or founded upon law or official or accepted rules", 1],
  ["legislate", "make laws, bills, etc. or bring into effect by legislation", 1],
  ["levy", "a charge imposed and collected", 10],
  ["liberal", "a person who favors a political philosophy of progress and reform and the protection of civil liberties", 5],
  ["licence", "excessive freedom; lack of due restraint; - Will Durant; - Edmund Burke", 5],
  ["likewise", "in like or similar manner; ; - Samuel Johnson", 10],
  ["link", "the means of connection between things linked in series", 3],
  ["locate", "discover the location of; determine the place of; find by searching or examining", 3],
  ["logic", "the branch of philosophy that analyzes inference", 5],
  ["maintain", "keep in a certain state, position, or activity; e.g.,", 2],
  ["major", "a commissioned military officer in the United States Army or Air Force or Marines; below lieutenant colonel and above captain", 1],
  ["manipulate", "influence or control shrewdly or deviously", 8],
  ["manual", "a small handbook", 9],
  ["margin", "the boundary line or the area immediately inside the boundary", 5],
  ["mature", "develop and reach maturity; undergo maturation", 9],
  ["maximise", "make the most of", 3],
  ["mechanism", "the atomic process that occurs during a chemical reaction", 4],
  ["media", "a means or instrumentality for storing or communicating information", 7],
  ["mediate", "act between parties with a view to reconciling differences", 9],
  ["medical", "a thorough physical examination; includes a variety of tests depending on the age and sex and health of the person", 5],
  ["medium", "a means or instrumentality for storing or communicating information", 9],
  ["mental", "involving the mind or an intellectual process", 5],
  ["method", "a way of doing something, especially a systematic way; implies an orderly logical arrangement (usually in steps)", 1],
  ["migrate", "move from one country or region to another and settle there", 6],
  ["military", "the military forces of a nation", 9],
  ["minimal", "the least possible", 9],
  ["minimise", "represent as less significant or important", 8],
  ["minimum", "the smallest possible quantity", 6],
  ["ministry", "religious ministers collectively (especially Presbyterian)", 6],
  ["minor", "a young person of either sex", 3],
  ["mode", "how something is done or how it happens", 7],
  ["modify", "make less severe or harsh or extreme", 5],
  ["monitor", "someone who supervises (an examination)", 5],
  ["motive", "the psychological feature that arouses an organism to action toward a desired goal; the reason for the action; that which gives purpose and direction to behavior", 6],
  ["mutual", "common to or shared by two or more parties", 9],
  ["negate", "be in contradiction with", 3],
  ["network", "an interconnected system of things or people", 5],
  ["neutral", "one who does not side with any party in a war or dispute", 6],
  ["nevertheless", "despite anything to the contrary (usually following a concession)", 6],
  ["nonetheless", "despite anything to the contrary (usually following a concession)", 10],
  ["norm", "a standard or model or pattern regarded as typical", 9],
  ["normal", "something regarded as a normative example", 2],
  ["notion", "a vague idea in which some confidence is placed", 5],
  ["notwithstanding", "despite anything to the contrary (usually following a concession)", 10],
  ["nuclear", "(weapons) deriving destructive energy from the release of atomic energy", 8],
  ["objective", "the goal intended to be attained (and which is believed to be attainable)", 5],
  ["obtain", "come into possession of", 2],
  ["obvious", "easily perceived by the senses or grasped by the mind", 4],
  ["occupy", "keep busy with", 4],
  ["occur", "come to pass", 1],
  ["odd", "not divisible by two", 10],
  ["offset", "the time at which something is supposed to begin", 8],
  ["ongoing", "currently happening", 10],
  ["option", "the right to buy or sell property at an agreed price; the right is purchased and if it is not exercised by a stated date the money is forfeited", 4],
  ["orient", "the countries of Asia", 5],
  ["outcome", "something that results", 3],
  ["output", "final product; the things produced", 4],
  ["overall", "(usually plural) work clothing consisting of denim trousers (usually with a bib and shoulder straps)", 4],
  ["overlap", "a representation of common ground between theories or phenomena", 9],
  ["overseas", "in a foreign country", 6],
  ["panel", "sheet that forms a distinct (usually flat and rectangular) section or component of something", 10],
  ["paradigm", "systematic arrangement of all the inflected forms of a word", 7],
  ["paragraph", "one of several distinct subdivisions of a text intended to separate ideas; the beginning is usually marked by a new indented line", 8],
  ["parallel", "something having the property of being analogous to something else", 4],
  ["parameter", "a constant in the equation of a curve that can be varied to yield a family of similar curves", 4],
  ["participate", "share in something", 2],
  ["partner", "a person's partner in marriage", 3],
  ["passive", "the voice used to indicate that the grammatical subject of the verb is the recipient (not the source) of the action denoted by the verb", 9],
  ["perceive", "to become aware of through the senses", 2],
  ["percent", "a proportion in relation to a whole (which is usually the amount per hundred)", 1],
  ["period", "an amount of time", 1],
  ["persist", "continue to exist", 10],
  ["perspective", "a way of regarding situations or topics etc", 5],
  ["phase", "any distinct time period in a sequence of events", 4],
  ["phenomenon", "any state or process known through the senses rather than by intuition or reasoning", 7],
  ["philosophy", "a belief (or system of beliefs) accepted as authoritative by some group or school", 3],
  ["physical", "involving the body as distinguished from the mind or spirit", 3],
  ["plus", "a useful or valuable quality", 8],
  ["policy", "a plan of action adopted by an individual or social group", 1],
  ["portion", "something determined in relation to something that includes it", 9],
  ["pose", "affected manners intended to impress others", 10],
  ["positive", "the primary form of an adjective or adverb; denotes a quality without qualification, comparison, or relation to increase or diminution", 2],
  ["potential", "the inherent capacity for coming into being", 2],
  ["practitioner", "someone who practices a learned profession", 8],
  ["precede", "be earlier in time; go back further", 6],
  ["precise", "sharply exact or accurate or delimited", 5],
  ["predict", "make a prediction about; tell in advance", 4],
  ["predominant", "most frequent or common", 8],
  ["preliminary", "a minor match preceding the main event", 9],
  ["presume", "take to be the case or to be true; accept without verification or proof", 6],
  ["previous", "just preceding something else in time or order", 2],
  ["primary", "a preliminary election where delegates or nominees are chosen", 2],
  ["prime", "a number that has no factor but itself and 1", 5],
  ["principal", "the original amount of a debt on which interest is calculated", 4],
  ["principle", "a basic generalization that is accepted as true and that can be used as a basis for reasoning or conduct", 1],
  ["prior", "the head of a religious order; in an abbey the prior is next below the abbot", 4],
  ["priority", "status established in order of importance or urgency", 7],
  ["proceed", "continue talking;  he continued,", 1],
  ["process", "a series of actions that produce a result", 1],
  ["professional", "a person engaged in one of the learned professions", 4],
  ["prohibit", "command against", 7],
  ["project", "any piece of work that is undertaken or attempted", 4],
  ["promote", "contribute to the progress or growth of", 4],
  ["proportion", "the quotient obtained when the magnitude of a part is divided by the magnitude of the whole", 3],
  ["prospect", "the possibility of future success", 8],
  ["protocol", "(computer science) rules determining the format and transmission of data", 9],
  ["psychology", "the science of mental life", 5],
  ["publication", "a copy of a printed work offered for distribution", 7],
  ["publish", "put into print", 3],
  ["purchase", "the acquisition of something for payment", 2],
  ["pursue", "carry out or participate in an activity; be involved in", 5],
  ["qualitative", "involving distinctions based on qualities", 9],
  ["quote", "a punctuation mark used to attribute the enclosed text to someone else", 7],
  ["radical", "(chemistry) two or more atoms bound together as a single unit and forming part of a molecule", 8],
  ["random", "lacking any definite plan or order or purpose; governed by or depending on chance", 8],
  ["range", "an area in which something acts or operates or has power or control:", 2],
  ["ratio", "the relative magnitudes of two quantities (usually expressed as a quotient)", 5],
  ["rational", "an integer or a fraction", 6],
  ["react", "show a response or a reaction to something", 3],
  ["recover", "get or find back; recover the use of", 6],
  ["refine", "improve or perfect by pruning or polishing", 9],
  ["regime", "the organization that is the governing authority of a political unit", 4],
  ["region", "the extended spatial location of something", 2],
  ["register", "an official written record of names or events or transactions", 3],
  ["regulate", "fix or adjust the time, amount, degree, or rate of", 2],
  ["reinforce", "make stronger", 8],
  ["reject", "the person or thing that is rejected or set aside as inferior in quality", 5],
  ["relax", "become less tense, rest, or take one's ease", 9],
  ["release", "merchandise issued for sale or public showing (especially a record or film)", 7],
  ["relevant", "having a bearing on or connection with the subject at issue", 2],
  ["reluctance", "(physics) opposition to magnetic flux (analogous to electric resistance)", 10],
  ["rely", "have confidence or faith in", 3],
  ["remove", "degree of figurative distance or separation;  or", 3],
  ["require", "require as useful, just, or proper", 1],
  ["research", "systematic investigation to establish facts", 1],
  ["reside", "make one's home in a particular place or community", 2],
  ["resolve", "the trait of being resolute", 4],
  ["resource", "available source of wealth; a new or reserve supply that can be drawn upon when needed", 2],
  ["respond", "show a response or a reaction to something", 1],
  ["restore", "return to its original or usable and functioning condition", 8],
  ["restrain", "keep under control; keep in check", 9],
  ["restrict", "place restrictions on", 2],
  ["retain", "hold back within", 4],
  ["reveal", "make visible", 6],
  ["revenue", "the entire amount of income before any deductions are made", 5],
  ["reverse", "a relation of direct opposition", 7],
  ["revise", "the act of rewriting something", 8],
  ["revolution", "a drastic and far-reaching change in ways of thinking and behaving", 9],
  ["rigid", "incapable of or resistant to bending", 9],
  ["role", "the function or position someone or something has", 1],
  ["route", "an established line of travel or access", 9],
  ["scenario", "an outline or synopsis of a play (or, by extension, of a literary work)", 9],
  ["schedule", "a temporally organized plan for matters to be attended to", 8],
  ["scheme", "an elaborate and systematic plan of action", 3],
  ["scope", "an area in which something acts or operates or has power or control:", 6],
  ["section", "a self-contained part of a larger composition (written or musical)", 1],
  ["sector", "a plane figure bounded by two radii and the included arc of a circle", 1],
  ["secure", "get by special effort", 2],
  ["seek", "the movement of a read/write head to a specific data track on a disk", 2],
  ["select", "pick out, select, or choose from a number of alternatives", 2],
  ["sequence", "serial arrangement in which things follow in logical order or a recurrent pattern", 3],
  ["series", "similar things placed in order or happening one after another", 4],
  ["sex", "activities associated with sexual intercourse", 3],
  ["shift", "an event in which something is displaced without rotation", 3],
  ["significant", "important or large enough to be noticeable", 1],
  ["similar", "marked by correspondence or resemblance", 1],
  ["simulate", "reproduce someone's behavior or looks", 7],
  ["site", "the piece of land on which something is located (or is to be located)", 2],
  ["so-called", "doubtful or suspect", 10],
  ["sole", "the underside of footwear or a golf club", 7],
  ["somewhat", "to a small degree or extent", 7],
  ["source", "a person, place, or thing that provides information", 1],
  ["specific", "a fact about some part (as opposed to general)", 1],
  ["specify", "specify as a condition or requirement in a contract or agreement; make an express demand or provision in an agreement", 3],
  ["sphere", "a particular environment or walk of life", 9],
  ["stable", "a farm building for housing horses or other livestock", 5],
  ["statistic", "a datum that can be represented numerically", 4],
  ["status", "the relative position or standing of things or especially persons in a society", 4],
  ["straightforward", "free from ambiguity", 10],
  ["strategy", "an elaborate and systematic plan of action", 2],
  ["stress", "the relative prominence of a syllable or musical note (especially with regard to stress or pitch)", 4],
  ["structure", "a thing constructed; a complex entity constructed of many parts", 1],
  ["style", "how something is done or how it happens", 5],
  ["submit", "refer for judgment or consideration", 7],
  ["subordinate", "an assistant subject to the authority or control of another", 9],
  ["subsequent", "following in time or order", 4],
  ["subsidy", "a grant paid by a government to an enterprise that benefits the public", 6],
  ["substitute", "a person or thing that takes or can take the place of another", 5],
  ["successor", "a person who follows next in order", 7],
  ["sufficient", "of a quantity that can fulfill a need or requirement but without being abundant", 3],
  ["sum", "a quantity of money", 4],
  ["summary", "a brief statement that presents the main points in a concise form", 4],
  ["supplement", "textual matter that is added onto a publication; usually at the end", 9],
  ["survey", "a detailed critical inspection", 2],
  ["survive", "continue to live through hardship or adversity", 7],
  ["suspend", "hang freely", 9],
  ["sustain", "lengthen or extend in duration or space", 5],
  ["symbol", "an arbitrary sign (written or printed) that has acquired a conventional significance", 5],
  ["tape", "a long thin piece of cloth or paper as used for binding or fastening", 6],
  ["target", "a reference point to shoot at", 5],
  ["task", "any piece of work that is undertaken or attempted", 3],
  ["team", "a cooperative unit (especially in sports)", 9],
  ["technical", "a pickup truck with a gun mounted on it", 3],
  ["technique", "a practical method or art applied to some particular task", 3],
  ["technology", "the practical application of science to commerce or industry", 3],
  ["temporary", "a worker (especially in an office) hired on a temporary basis", 9],
  ["tense", "a grammatical category of verbs used to express distinctions of time", 8],
  ["terminate", "bring to an end or halt", 8],
  ["text", "the words of something written", 2],
  ["theme", "the subject matter of a conversation or discussion", 8],
  ["theory", "a well-substantiated explanation of some aspect of the natural world; an organized system of accepted knowledge that applies in a variety of circumstances to explain a specific set of phenomena", 1],
  ["thereby", "by that means or because of that", 8],
  ["thesis", "an unproved statement put forward as a premise in an argument", 7],
  ["topic", "the subject matter of a conversation or discussion", 7],
  ["trace", "a just detectable amount", 6],
  ["tradition", "an inherited pattern of thought or action", 2],
  ["transfer", "the act of moving something from one location to another", 2],
  ["transform", "subject to a mathematical transformation", 6],
  ["transit", "a surveying instrument for measuring horizontal and vertical angles, consisting of a small telescope mounted on a tripod", 5],
  ["transmit", "transfer to another", 7],
  ["transport", "something that serves as a means of transportation", 6],
  ["trend", "a general direction in which something tends to move", 5],
  ["trigger", "lever that activates the firing mechanism of a gun", 9],
  ["ultimate", "the finest or most superior quality of its kind", 7],
  ["undergo", "pass through", 10],
  ["underlie", "be or form the base for", 6],
  ["undertake", "enter upon an activity or enterprise", 4],
  ["uniform", "clothing of distinctive design worn by members of a particular group as a means of identification", 8],
  ["unify", "become one", 9],
  ["unique", "radically distinctive and without equal", 7],
  ["utilise", "put into service; make work or employ for a particular purpose or for its inherent or natural purpose", 6],
  ["valid", "well grounded in logic or truth or having legal force", 3],
  ["vary", "become different in some particular way, without permanently losing one's or its former characteristics or essence", 1],
  ["vehicle", "a conveyance that transports people or objects", 8],
  ["version", "an interpretation of a matter from a particular viewpoint", 5],
  ["via", "an academic word from frequency sublist 8", 8],
  ["violate", "fail to agree with; be in violation of; as of rules or patterns", 9],
  ["virtual", "being actually such in almost every respect", 8],
  ["visible", "capable of being seen; or open to easy view", 7],
  ["vision", "a vivid mental image", 9],
  ["visual", "relating to or using sight", 8],
  ["volume", "the amount of 3-dimensional space occupied by an object", 3],
  ["voluntary", "(military) a person who freely enlists for service", 7],
  ["welfare", "governmental provision of economic assistance to persons in need", 5],
  ["whereas", "an academic word from frequency sublist 5", 5],
  ["whereby", "an academic word from frequency sublist 10", 10],
  ["widespread", "widely circulated or diffused", 8],
] as const;
