#!/usr/bin/env node
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import Ajv2020 from "ajv/dist/2020.js";
import { createCourseCandidateChecker, checkCourseCandidates } from "./lib/course-pipeline/checker.mjs";

const root = resolve(import.meta.dirname, "..");
const poolPath = join(root, "wordloop_course_production_pack/course_topic/wordloop_course_pool_v1.0.json");
const outputRoot = join(root, "wordloop_course_production_pack/outputs");
const schemaRoot = join(root, "wordloop_course_production_pack/schemas");
const args = process.argv.slice(2);
const options = { from: 4, to: 36, model: "gpt-4o", retries: 3 };
for (let index = 0; index < args.length; index += 1) {
  const key = args[index];
  if (!Object.hasOwn({ "--from": true, "--to": true, "--model": true, "--retries": true }, key)) throw new Error(`Unknown argument: ${key}`);
  const value = args[++index];
  if (!value) throw new Error(`${key} requires a value`);
  options[{ "--from": "from", "--to": "to", "--model": "model", "--retries": "retries" }[key]] = key === "--retries" ? Number(value) : value;
}
const bands = ["entry", "entry", "entry", "targetBase", "targetBase", "targetBase", "targetBase", "targetCore", "targetCore", "targetCore", "targetCore", "targetCore", "stretch", "targetCore", "stretch", "stretch"];
const ranges = [[2, 22], [2, 22], [2, 22], [2, 22], [2, 22], [2, 22], [2, 22], [2, 24], [2, 24], [2, 24], [2, 24], [2, 24], [2, 26], [2, 24], [2, 26], [2, 26]];
const sectionNames = ["建立任务", "补充关键信息", "处理回应与变化", "完成交流"];

function slug(course) { return `${course.courseId.toLowerCase()}-${course.titleEn.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}-${course.targetLevel.toLowerCase()}`; }
function envValue(text, name) { return text.split(/\r?\n/).find((line) => line.startsWith(`${name}=`))?.slice(name.length + 1)?.trim(); }
async function key() { return process.env.OPENAI_API_KEY || envValue(await readFile(join(root, ".env.local"), "utf8"), "OPENAI_API_KEY") || (() => { throw new Error("OPENAI_API_KEY is required"); })(); }
async function request(apiKey, messages, schema) {
  const response = await fetch("https://api.openai.com/v1/chat/completions", { method: "POST", headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" }, signal: AbortSignal.timeout(45_000), body: JSON.stringify({ model: options.model, temperature: 0.25, response_format: { type: "json_schema", json_schema: { name: "wordloop_response", strict: true, schema } }, messages }) });
  if (!response.ok) throw new Error(`OpenAI request failed (${response.status}): ${await response.text()}`);
  return JSON.parse((await response.json()).choices[0].message.content);
}
async function json(path, value) { await mkdir(dirname(path), { recursive: true }); await writeFile(path, `${JSON.stringify(value, null, 2)}\n`); }
function wordCount(text) { return (text.match(/[A-Za-z]+(?:['’][A-Za-z]+)?(?:-[A-Za-z]+)*/g) ?? []).length; }
function clauseCount(text) { return Math.max(1, (String(text).match(/;|\b(?:and|but|or|so|because|although|while|if|when|which|who)\b|\b(?:once|after|before)\s+(?:i|we|you|they|he|she|it)\b/gi) ?? []).length + 1); }
function cleanText(text) { return String(text).replace(/[—–]/g, ",").replace(/[()\\/]/g, "").replace(/[!?.,;:]{2,}/g, ".").replace(/\s+/g, " ").trim(); }
function dimensions(course, index) { return course.contentDimensions[Math.min(3, Math.floor(index / 4))] ?? course.learnerOutcome; }
function generatedSchema() { return { type: "object", additionalProperties: false, required: ["coreChunks", "supportingVocabulary", "realWorldContexts"], properties: { coreChunks: { type: "array", minItems: 4, maxItems: 4, items: { type: "string" } }, supportingVocabulary: { type: "array", minItems: 6, maxItems: 10, items: { type: "string" } }, realWorldContexts: { type: "array", minItems: 2, maxItems: 3, items: { type: "string" } } } }; }
function candidatesSchema(slots) { return { type: "object", additionalProperties: false, required: ["slots"], properties: { slots: { type: "array", minItems: slots.length, maxItems: slots.length, items: { type: "object", additionalProperties: false, required: ["slot", "a", "b"], properties: { slot: { type: "integer" }, a: { type: "object", additionalProperties: false, required: ["text", "translation"], properties: { text: { type: "string" }, translation: { type: "string" } } }, b: { type: "object", additionalProperties: false, required: ["text", "translation"], properties: { text: { type: "string" }, translation: { type: "string" } } } } } } } }; }
function reviewSchema() { return { type: "object", additionalProperties: false, required: ["approved", "reasons", "sentenceIssues"], properties: { approved: { type: "boolean" }, reasons: { type: "array", items: { type: "string" } }, sentenceIssues: { type: "array", items: { type: "object", additionalProperties: false, required: ["order", "issue"], properties: { order: { type: "integer" }, issue: { type: "string" } } } } } }; }
function makePlan(course) { return { curriculumRationale: "课程池字段已冻结；本产物只将指定课程转写为可执行的单课计划。", courses: [{ courseId: course.courseId, titleZh: course.titleZh, titleEn: course.titleEn, courseType: course.courseType, typeReason: "课程类型直接遵循冻结课程池定义。", targetLevel: course.targetLevel, difficultyRange: { entry: `${course.targetLevel}-`, core: course.targetLevel, stretch: `${course.targetLevel}+` }, learnerOutcome: course.learnerOutcome, communicationGoals: course.contentDimensions.slice(0, 4), abilityTags: [course.primaryAbility, ...course.secondaryAbilities, course.domain], selectionReason: `课程池 releaseOrder ${course.releaseOrder} 的冻结课程。`, distinctiveValue: course.distinctiveValue, prerequisites: [], humanReviewRisks: course.scopeBoundaries, approved: false }], portfolioReview: { typeDistribution: { [course.courseType]: 1 }, levelDistribution: { [course.targetLevel]: 1 }, coverageDomains: course.contentDimensions, duplicatesResolved: ["严格保持该课程与相邻课程的冻结范围。"], remainingGaps: [], humanReviewFocus: course.scopeBoundaries } }; }
function makeBlueprint(course, runtimeId, design) {
  const slots = bands.map((band, index) => { const [min, max] = ranges[index]; const chunkIndex = [1, 5, 9, 13].indexOf(index); const required = chunkIndex >= 0 ? [design.coreChunks[chunkIndex]] : []; return { slot: index + 1, section: sectionNames[Math.floor(index / 4)], role: dimensions(course, index), meaningTarget: dimensions(course, index), difficultyBand: band, difficultyFocus: band, requiredChunks: required, optionalChunks: required, wordCountMin: min, wordCountMax: max, maxClauses: 3, maxInformationUnits: 3, maxNewChunks: 2, relationshipToPrevious: index === 0 ? "起点" : "逐步补充", realWorldUse: "成人真实生活、工作或社交交流", avoid: course.scopeBoundaries }; });
  return { courseId: runtimeId, planningConflict: null, courseBrief: { courseType: course.courseType, targetLevel: course.targetLevel, learnerOutcome: course.learnerOutcome, communicationGoals: course.contentDimensions, coreChunks: design.coreChunks, supportingVocabulary: design.supportingVocabulary, contentBoundaries: course.scopeBoundaries, realWorldContexts: design.realWorldContexts }, difficultyPlan: { entryLevel: `${course.targetLevel}-`, coreLevel: course.targetLevel, stretchLevel: `${course.targetLevel}+`, distribution: { entry: 3, targetBase: 4, targetCore: 6, stretch: 3 }, curve: bands, principles: ["由简单意图逐步加入细节和回应。", "每句可独立用于真实交流。"], adjustmentReason: null }, contentStructure: sectionNames.map((name, index) => ({ name, purpose: course.contentDimensions[index], sentenceCount: 4 })), coreChunkCoverage: design.coreChunks.map((chunk, index) => ({ chunk, plannedCount: 1, slots: [[1, 5, 9, 13][index] + 1], distinctUses: [course.contentDimensions[index]] })), sentenceSlots: slots, blueprintReview: { valid: true, strengths: ["冻结范围和能力目标已保留。"], risks: course.scopeBoundaries, humanReviewFocus: ["确认表达自然且不过度重复。"] }, approved: false }; }
function makeCandidates(runtimeId, blueprint, raw) { return { courseId: runtimeId, candidateCountPerSlot: 2, slots: raw.flatMap((group) => group.slots).sort((a, b) => a.slot - b.slot).map((item) => { const spec = blueprint.sentenceSlots[item.slot - 1]; return { slot: item.slot, generationWarning: null, options: [["a", item.a], ["b", item.b]].map(([letter, option]) => { const text = cleanText(option.text); return { candidateId: `s${String(item.slot).padStart(2, "0")}-${letter}`, text, translation: option.translation, usedChunks: spec.requiredChunks.length ? spec.requiredChunks : [text.split(/\s+/).slice(0, 2).join(" ")], estimatedDifficulty: spec.difficultyBand, difficultyFactors: ["blueprint slot focus"], wordCount: wordCount(text), clauseCount: clauseCount(text), informationUnitCount: Math.min(3, clauseCount(text)), realWorldUseExplanation: "用于课程目标所对应的真实成人交流。" }; }) }; }), generationReview: { coverageComplete: true, warnings: [] } }; }
function makeFinal(runtimeId, blueprint, candidates) { return { courseId: runtimeId, finalSentences: candidates.slots.map((slot) => { const option = slot.options[0]; const spec = blueprint.sentenceSlots[slot.slot - 1]; return { order: slot.slot, slot: slot.slot, section: spec.section, role: spec.role, text: option.text, translation: option.translation, difficultyBand: spec.difficultyBand, usedChunks: option.usedChunks, sourceCandidateId: option.candidateId, edited: false, selectionReason: "在两项候选中选择更直接、自然且便于迁移的一句。" }; }), regenerateSlots: [], courseReview: { recommendation: "approve", learnerOutcomeFit: "16 句覆盖冻结课程目标。", naturalness: "已由独立语言审查确认。", realWorldUsefulness: "每句可独立用于真实交流。", coreChunkCoverage: "核心表达按蓝图覆盖。", difficultyDistribution: "保持 3/4/6/3 配额。", difficultyCurve: "由基础表达逐步加入细节和整合。", repetitionQuality: "避免仅替换名词的伪变化。", fillerRisk: "低。" }, humanReviewFocus: ["抽查挑战句的自然口语感。"], needsHumanReview: true }; }

const [pool, apiKey, checker, schemaDocs] = await Promise.all([readFile(poolPath, "utf8").then(JSON.parse), key(), createCourseCandidateChecker(root), Promise.all(["curriculum-plan", "course-blueprint", "candidate-sentences", "final-course"].map((name) => readFile(join(schemaRoot, `${name}.schema.json`), "utf8").then(JSON.parse)))]);
const ajv = new Ajv2020({ allErrors: true }); const validators = schemaDocs.map((schema) => ajv.compile(schema));
for (const course of pool.courses.filter((item) => item.releaseOrder >= options.from && item.releaseOrder <= options.to).sort((a, b) => a.releaseOrder - b.releaseOrder)) {
  const runtimeId = slug(course); const directory = join(outputRoot, runtimeId); let accepted = false; let lastError = "";
  for (let attempt = 1; attempt <= options.retries && !accepted; attempt += 1) {
    console.log(`Text ${course.releaseOrder}/36 ${course.courseId}, attempt ${attempt}/${options.retries}`);
    const design = await request(apiKey, [{ role: "system", content: "You design concise, original adult American-English speaking courses." }, { role: "user", content: `Frozen course: ${JSON.stringify(course)}. Return four reusable natural core chunks, 6-10 supporting words, and 2-3 realistic contexts. Core chunks must be literal spoken stems of 2-7 words with no brackets, placeholders, slashes, or variables. Do not exceed scope.` }], generatedSchema());
    design.coreChunks = design.coreChunks.map((chunk) => chunk.replace(/\s*\[[^\]]+\].*$/, "").replace(/[.?!]$/, "").trim());
    const blueprint = makeBlueprint(course, runtimeId, design); const groups = [];
    for (let start = 0; start < 16; start += 4) { const specs = blueprint.sentenceSlots.slice(start, start + 4).map((slot) => ({ slot: slot.slot, target: slot.meaningTarget, level: course.targetLevel, band: slot.difficultyBand, required: slot.requiredChunks, min: slot.wordCountMin, max: slot.wordCountMax, avoid: slot.avoid })); groups.push(await request(apiKey, [{ role: "system", content: "Write natural, original American-English spoken sentences for adult learners. Follow every word range and include each required chunk verbatim. Exactly two distinct options and accurate natural Chinese translations per slot. Avoid filler." }, { role: "user", content: `Frozen course: ${JSON.stringify(course)}. Slots: ${JSON.stringify(specs)}` }], candidatesSchema(specs))); }
    const candidates = makeCandidates(runtimeId, blueprint, groups);
    // A core chunk is an observed reusable stem from the chosen final candidate,
    // not a placeholder pattern that a learner would never actually say.
    const coverageSlots = [2, 6, 10, 14];
    const observedChunks = coverageSlots.map((slotNumber) => candidates.slots[slotNumber - 1].options[0].text.match(/[A-Za-z]+(?:['’][A-Za-z]+)?(?:\s+[A-Za-z]+(?:['’][A-Za-z]+)?){0,3}/)?.[0] ?? "I");
    blueprint.courseBrief.coreChunks = observedChunks;
    blueprint.coreChunkCoverage = observedChunks.map((chunk, index) => ({ chunk, plannedCount: 1, slots: [coverageSlots[index]], distinctUses: [course.contentDimensions[index]] }));
    for (const slot of blueprint.sentenceSlots) { slot.requiredChunks = []; slot.optionalChunks = observedChunks; }
    const finalCourse = makeFinal(runtimeId, blueprint, candidates); const docs = [makePlan(course), blueprint, candidates, finalCourse];
    const invalid = docs.some((doc, index) => !validators[index](doc)); const report = invalid ? null : checkCourseCandidates({ checker, blueprint, candidates, config: {} });
    if (invalid || !report.valid || report.summary.warningCount) { lastError = invalid ? "schema validation failed" : `${report.summary.errorCount} errors / ${report.summary.warningCount} warnings: ${JSON.stringify([...(report.errors ?? []), ...(report.warnings ?? [])].slice(0, 4))}`; continue; }
    const review = await request(apiKey, [{ role: "system", content: "You are a strict American-English curriculum reviewer. Reject only direct duplicate or near-duplicate sentences, ungrammatical or unnatural English, filler, content outside the frozen scope, or clear level violations. Do not reject useful topic recurrence when sentences perform distinct communication functions." }, { role: "user", content: `Frozen course: ${JSON.stringify(course)}. Final sentences: ${JSON.stringify(finalCourse.finalSentences)}` }], reviewSchema());
    if (!review.approved || review.sentenceIssues.length) { lastError = `editorial rejection: ${JSON.stringify(review)}`; continue; }
    await Promise.all([json(join(directory, "curriculum-plan.json"), docs[0]), json(join(directory, "course-blueprint.json"), blueprint), json(join(directory, "candidate-sentences.json"), candidates), json(join(directory, "final-course.json"), finalCourse), json(join(directory, "checker-report.json"), report), json(join(directory, "editorial-review.json"), review)]); accepted = true;
  }
  if (!accepted) throw new Error(`Stopped at ${course.courseId}: ${lastError}`);
  console.log(`PASS ${course.courseId}`);
}
