import Foundation

struct CompletionDialogCopy: Sendable {
    let kicker: String
    let restartTitle: String
    let completedTitle: String
    let restartMessage: String
    let completedMessage: String
    let cancel: String
    let chooseCourse: String
    let restart: String
    let practiceAgain: String
    let resetError: String

    static var current: Self {
        let id = (Locale.preferredLanguages.first ?? Locale.current.identifier).lowercased()
        if id.hasPrefix("zh-hant") || id.contains("zh-tw") || id.contains("zh-hk") { return Self(kicker: "課程完成", restartTitle: "這門課程已完成", completedTitle: "課程學完了", restartMessage: "要重新開始練習嗎？現有進度將被清除。", completedMessage: "太棒了。你可以從頭再練一次，或選擇下一門課繼續學習。", cancel: "取消", chooseCourse: "選擇課程", restart: "重新開始", practiceAgain: "再練一次", resetError: "暫時無法重設進度，請稍後再試。") }
        if id.hasPrefix("zh") { return Self(kicker: "课程完成", restartTitle: "这门课程已经完成", completedTitle: "这门课程学完了", restartMessage: "要重新开始练习吗？现有进度将被清零。", completedMessage: "太棒了。你可以从头再练一遍，或者挑选下一门课程继续学习。", cancel: "取消", chooseCourse: "选择课程", restart: "重新开始", practiceAgain: "再练一次", resetError: "暂时无法重置进度，请稍后重试。") }
        if id.hasPrefix("ja") { return Self(kicker: "コース完了", restartTitle: "このコースは完了しました", completedTitle: "コースを学習し終えました", restartMessage: "最初から練習し直しますか？現在の進捗はリセットされます。", completedMessage: "すばらしいです。最初からもう一度練習するか、次のコースを選べます。", cancel: "キャンセル", chooseCourse: "コースを選択", restart: "最初からやり直す", practiceAgain: "もう一度練習", resetError: "進捗をリセットできません。後でもう一度お試しください。") }
        if id.hasPrefix("ko") { return Self(kicker: "코스 완료", restartTitle: "이 코스를 완료했습니다", completedTitle: "코스 학습을 마쳤습니다", restartMessage: "처음부터 다시 연습할까요? 현재 진도가 초기화됩니다.", completedMessage: "대단해요. 처음부터 다시 연습하거나 다음 코스를 선택할 수 있습니다.", cancel: "취소", chooseCourse: "코스 선택", restart: "처음부터 다시 시작", practiceAgain: "다시 연습", resetError: "진도를 초기화할 수 없습니다. 나중에 다시 시도해 주세요.") }
        if id.hasPrefix("es") { return Self(kicker: "CURSO COMPLETADO", restartTitle: "Has completado este curso", completedTitle: "Has terminado el curso", restartMessage: "¿Quieres volver a practicar desde el principio? Se borrará el progreso actual.", completedMessage: "¡Excelente! Puedes practicarlo otra vez desde el principio o elegir el siguiente curso.", cancel: "Cancelar", chooseCourse: "Elegir curso", restart: "Empezar de nuevo", practiceAgain: "Practicar otra vez", resetError: "No se pudo restablecer el progreso. Inténtalo más tarde.") }
        if id.hasPrefix("pt") { return Self(kicker: "CURSO CONCLUÍDO", restartTitle: "Você concluiu este curso", completedTitle: "Você terminou o curso", restartMessage: "Quer praticar desde o início? O progresso atual será apagado.", completedMessage: "Muito bem! Você pode praticar novamente desde o início ou escolher o próximo curso.", cancel: "Cancelar", chooseCourse: "Escolher curso", restart: "Começar de novo", practiceAgain: "Praticar novamente", resetError: "Não foi possível redefinir o progresso. Tente novamente mais tarde.") }
        if id.hasPrefix("fr") { return Self(kicker: "COURS TERMINÉ", restartTitle: "Vous avez terminé ce cours", completedTitle: "Vous avez terminé le cours", restartMessage: "Voulez-vous recommencer depuis le début ? La progression actuelle sera effacée.", completedMessage: "Bravo ! Vous pouvez le refaire depuis le début ou choisir le cours suivant.", cancel: "Annuler", chooseCourse: "Choisir un cours", restart: "Recommencer", practiceAgain: "Pratiquer encore", resetError: "Impossible de réinitialiser la progression. Réessayez plus tard.") }
        if id.hasPrefix("de") { return Self(kicker: "KURS ABGESCHLOSSEN", restartTitle: "Du hast diesen Kurs abgeschlossen", completedTitle: "Du hast den Kurs beendet", restartMessage: "Möchtest du von vorne üben? Der aktuelle Fortschritt wird gelöscht.", completedMessage: "Klasse! Du kannst von vorne weiterüben oder den nächsten Kurs auswählen.", cancel: "Abbrechen", chooseCourse: "Kurs auswählen", restart: "Neu beginnen", practiceAgain: "Noch einmal üben", resetError: "Der Fortschritt konnte nicht zurückgesetzt werden. Bitte später erneut versuchen.") }
        if id.hasPrefix("it") { return Self(kicker: "CORSO COMPLETATO", restartTitle: "Hai completato questo corso", completedTitle: "Hai terminato il corso", restartMessage: "Vuoi ricominciare dall’inizio? I progressi attuali verranno cancellati.", completedMessage: "Ottimo! Puoi ripeterlo dall’inizio oppure scegliere il corso successivo.", cancel: "Annulla", chooseCourse: "Scegli corso", restart: "Ricomincia", practiceAgain: "Ripeti", resetError: "Impossibile reimpostare i progressi. Riprova più tardi.") }
        if id.hasPrefix("ru") { return Self(kicker: "КУРС ЗАВЕРШЁН", restartTitle: "Вы завершили этот курс", completedTitle: "Вы закончили курс", restartMessage: "Начать практику заново? Текущий прогресс будет удалён.", completedMessage: "Отлично! Можно пройти курс ещё раз или выбрать следующий.", cancel: "Отмена", chooseCourse: "Выбрать курс", restart: "Начать заново", practiceAgain: "Повторить", resetError: "Не удалось сбросить прогресс. Повторите попытку позже.") }
        if id.hasPrefix("ar") { return Self(kicker: "اكتملت الدورة", restartTitle: "لقد أكملت هذه الدورة", completedTitle: "لقد أنهيت الدورة", restartMessage: "هل تريد التدريب من البداية؟ ستُحذف بيانات التقدم الحالية.", completedMessage: "رائع! يمكنك التدريب عليها من البداية أو اختيار الدورة التالية.", cancel: "إلغاء", chooseCourse: "اختيار دورة", restart: "البدء من جديد", practiceAgain: "التدرب مرة أخرى", resetError: "تعذّر إعادة ضبط التقدم. حاول لاحقًا.") }
        if id.hasPrefix("id") { return Self(kicker: "KURSUS SELESAI", restartTitle: "Anda telah menyelesaikan kursus ini", completedTitle: "Anda telah menyelesaikan kursus", restartMessage: "Mulai latihan dari awal? Kemajuan saat ini akan dihapus.", completedMessage: "Hebat! Anda dapat berlatih lagi dari awal atau memilih kursus berikutnya.", cancel: "Batal", chooseCourse: "Pilih kursus", restart: "Mulai lagi", practiceAgain: "Berlatih lagi", resetError: "Kemajuan tidak dapat direset. Coba lagi nanti.") }
        if id.hasPrefix("th") { return Self(kicker: "เรียนจบบทเรียน", restartTitle: "คุณเรียนบทเรียนนี้จบแล้ว", completedTitle: "คุณเรียนจบบทเรียนแล้ว", restartMessage: "ต้องการฝึกใหม่ตั้งแต่ต้นไหม ความคืบหน้าปัจจุบันจะถูกลบ", completedMessage: "ยอดเยี่ยม คุณฝึกตั้งแต่ต้นอีกครั้งหรือเลือกบทเรียนถัดไปได้", cancel: "ยกเลิก", chooseCourse: "เลือกบทเรียน", restart: "เริ่มใหม่", practiceAgain: "ฝึกอีกครั้ง", resetError: "รีเซ็ตความคืบหน้าไม่ได้ ลองใหม่ภายหลัง") }
        if id.hasPrefix("vi") { return Self(kicker: "ĐÃ HOÀN THÀNH KHÓA HỌC", restartTitle: "Bạn đã hoàn thành khóa học này", completedTitle: "Bạn đã học xong khóa học", restartMessage: "Bạn muốn luyện lại từ đầu không? Tiến độ hiện tại sẽ bị xóa.", completedMessage: "Tuyệt vời! Bạn có thể luyện lại từ đầu hoặc chọn khóa học tiếp theo.", cancel: "Hủy", chooseCourse: "Chọn khóa học", restart: "Bắt đầu lại", practiceAgain: "Luyện lại", resetError: "Không thể đặt lại tiến độ. Hãy thử lại sau.") }
        if id.hasPrefix("tr") { return Self(kicker: "KURS TAMAMLANDI", restartTitle: "Bu kursu tamamladın", completedTitle: "Kursu bitirdin", restartMessage: "Baştan pratik yapmak ister misin? Mevcut ilerlemen silinecek.", completedMessage: "Harika! Baştan tekrar pratik yapabilir veya sonraki kursu seçebilirsin.", cancel: "İptal", chooseCourse: "Kurs seç", restart: "Yeniden başla", practiceAgain: "Tekrar pratik yap", resetError: "İlerleme sıfırlanamadı. Daha sonra tekrar deneyin.") }
        return Self(kicker: "COURSE COMPLETE", restartTitle: "You completed this course", completedTitle: "You finished the course", restartMessage: "Restart practice from the beginning? Your current progress will be cleared.", completedMessage: "Great job. Practice it again from the beginning or choose the next course.", cancel: "Cancel", chooseCourse: "Choose course", restart: "Restart", practiceAgain: "Practice again", resetError: "Unable to reset progress. Please try again later.")
    }
}
